- content/cli.mdx
- layouts/CliReferenceLayout.tsx
* Adds `knock commit list` and `knock commit get` to the docs
* Improves `knock commit promote` section to include individual commit promotion.
[KNO-4636](https://linear.app/knock/issue/KNO-4636/[docs]-update-cli-knock-commit-docs)
> feat(KNO-4636): Add individual promotion docs

- content/mapi.mdx
- layouts/MapiReferenceLayout.tsx
Adds the following sections to the Management Api reference:
* Commit description
* Commits get endpoint
* Commits list endpoint
* Commits promote one endpoint
[KNO-4647](https://linear.app/knock/issue/KNO-4647/[docs]-update-management-api-reference)
https://github.com/knocklabs/docs/assets/67347884/d6a72d19-7ed2-4d6e-b263-9d31c4dcb780
> feat(KNO-4647) Update management api reference

- content/concepts/workflows.mdx
We are redirecting to localhost instead of `docs.knock.app`
[KNO-4749](https://linear.app/knock/issue/KNO-4749/[docs]-fix-workflow-preferences-link)
> chore(KNO-4749): Fix workflow preferences link

- content/concepts/schedules.mdx
- content/concepts/workflows.mdx
- content/reference.mdx
Add changes related to one-off schedules in the main `schedules` page and in the `API reference`.
IMPORTANT: Do not merge until we ship one-off schedule support: https://github.com/knocklabs/switchboard/pull/1719
[KNO-4646](https://linear.app/knock/issue/KNO-4646/[docs]-add-one-off-schedules-to-our-docs)
> feat(KNO-4646): Add one-off schedules to Docs

- content/managing-recipients/identifying-recipients.mdx
- content/reference.mdx
Quick doc update to clarify adding IDs to recipients & actors.
KNO-4752
> chore(kno-4752): clarify inline identify requires id fields

- components/PageNav.tsx
At screen widths >= to 1280px, the `<aside>` component which renders the "On This Page" sidebar has a height which overlaps the footer. This means that the "Visit website" and "Contact us" links are unusable, because the rollover is not detected.
This PR increases the height calc from 95px to 200px (thus decreasing overall component height) to leave enough clearance for the links to remain clickable.
> fix: decrease <aside> height to prevent footer overlap

- content/integrations/email/aws-ses.mdx
- content/integrations/email/mailersend.mdx
- content/integrations/email/mailgun.mdx
- content/integrations/email/mailjet.mdx
- content/integrations/email/mandrill.mdx
- content/integrations/email/postmark.mdx
- content/integrations/email/sendgrid.mdx
- content/integrations/email/sparkpost.mdx
Updating the "Getting Started" section for the different supported providers under integrations > email to all point users to "Integrations > Channels" from the dashboard.
Note that Mailtrap had already been updated.
> fix: update getting started section under supported email providers

- content/concepts/preferences.mdx
I updated the `Remember:...` section of text below [this code sample](https://docs.knock.app/concepts/preferences#combining-preferences) to be a callout. This change aligns it with the other uses of callouts the on concepts pages and better highlights an important caveat for the customer. 
Before
After
> add callout for combined prefs

- content/developer-tools/service-tokens.mdx
Updated instructions on where to go to generate a service token for better clarity. Also updated the note about only seeing a service token once upon generation to be a callout to better align with similar use cases of callouts.
Before:
After:
> fix: update service tokens page

- content/in-app-ui/react/feed.mdx
We currently document the ability to change the default value of `colorMode` for a given notification feed from `light` to `dark` by passing a `colorMode` prop to the `NotificationFeed` component. However, this setting is pulled from `KnockFeedProvider` by both `NotificationFeed` ([here](https://github.com/knocklabs/react-notification-feed/blob/f7eadca7726222d219ac1394764db2d6f5b0ff47/src/components/NotificationFeed/NotificationFeed.tsx#L77C51-L77C65)) and `NotificationFeedPopover` ([here](https://github.com/knocklabs/react-notification-feed/blob/f7eadca7726222d219ac1394764db2d6f5b0ff47/src/components/NotificationFeedPopover/NotificationFeedPopover.tsx#L40)) with the `useKnockFeed()` method. The `colorMode` prop is not valid for either of these components.
This PR simply changes the …
> fix: update dark mode instructions to pass prop directly to KnockFeedProvider

- content/integrations/extensions/segment.mdx
This PR makes 2 small clarifications to our Segment Extension documentation:
1. Add backticks to `track` to clarify that it is a Segment `event` type
2. Add an example event payload so that customers can see what Knock is sending to Segment
**Question:** Should we be using `<a target="_blank">` for external links, or should we be leaving these in pure MD even though it will direct users away from our site? I noticed that we are not currently preventing navigation away from the Knock docs with the link to Segment at the top of this particular page ([line 9](https://github.com/knocklabs/docs/blob/38d6a33fbae01bbb8ab95ea2657d8a2b3112cf06/content/integrations/extensions/segment.mdx#L9))
> chore: add payload example for Segment Track events

- content/in-app-ui/ios/overview.mdx
- content/in-app-ui/javascript/overview.mdx
- content/in-app-ui/react-native/overview.mdx
- content/in-app-ui/react/overview.mdx
Currently, the[ "Provide Feedback"](https://docs.knock.app/in-app-ui/react-native/overview#provide-feedback) section of the React Native docs points users to a private repository, resulting in a 404. This PR removes that link for now and will be added back once that becomes open source.
Additionally, I've updated instructions on how to contact the team as the "Feedback" button is no longer available. Instead, I direct users to use the help dropdown to contact support.
> fix: update "provide feedback" section of RN docs + how to contact the team

- content/integrations/push/apns.mdx
This PR adds documentation from Pigeon to inform customers of a required conversion that is necessary before they supply their APNS certificate and private key to the channel configuration in their dashboard. Needs review for content accuracy.
> chore: add Pigeon conversion instructions link to cert-based APNS setup instructions

- content/integrations/extensions/segment.mdx
This PR updates the Segment extension page to be consistent with `code` styling for all of Segment's event types and names.
> fix: update styling for Segment event types and names

- content/in-app-ui/react/feed.mdx
Adds a recipe describing the default behavior of the `action_url` on the `KnockFeedProvider`. I put it first since its the most common scenario.
> fix: add default action_url behavior

- content/in-app-ui/react/preferences.mdx
Updates this code sample to use `Knock` as a default export instead of a named export. Checked these places:
https://github.com/knocklabs/knock-client-js/blob/main/src/index.ts
https://github.com/knocklabs/knock-node-example-app/blob/main/app/users/components/NotificationPreferencesModal.tsx
Before
After
> fix: change named to default import

- content/designing-workflows/branch-function.mdx
There is a branch limitation spelled out in the UI text 'Knock will execute the first branch whose conditions evaluate to true' that should also appear in the actual text of the docs.
Before
After
> chore: add limitation to doc text

- content/in-app-ui/ios/reference.mdx
- content/in-app-ui/react-native/notification-feeds.mdx
- content/in-app-ui/react/feed.mdx
Some customers have been confused about how to secure the notification feed. This adds relevant context to our in-app feed docs, linking back to the guide on securing the feeds.
KNO-4899
> chore(kno-4899): clarify security requirements for in-app feed docs

- content/reference.mdx
Updates the `Api reference` section adding the new `workflow categories` param.
To be more specific, this param was added to the following endpoint sections:
* GET /users/:id/messages
* GET /messages
* GET /objects/:collection/:id/messages
* GET /users/:user_id/feeds/:feed_id
This PR also includes a change to the notification `source` in the JSON response example, so now it includes `categories`.
[KNO-4921](https://linear.app/knock/issue/KNO-4921/[docs]-add-workflow-categories-filter-to-messagesfeed-api-reference)
> feat(KNO-4921): Update api reference with workflow categories

- components/Meta.tsx
Fixes an issue where canonical links are current [slug] because of 'pathname' being used.
> Fix canonical links for all docs

- content/concepts/users.mdx
- content/reference.mdx
In response to user feedback about lacking documentation of the `timezone` parameter for User objects, this PR updates both the concept page for Users (/concepts/users) and the API reference for identifying a user (/reference#identify-user) in order to clarify its usage.
> chore: add timezone information to user concept page and API reference

- content/reference.mdx
I find the existing English-language descriptions for the `/messages/:id/:status` endpoint (both `PUT` and `DELETE` methods) to be confusing. This PR attempts to clarify functionality by tweaking the descriptions.
> chore: update `/messages/:id/:status` endpoint descriptions to clarify functionality

- content/in-app-ui/react/migrating-from-react-notification-feed.mdx
- content/in-app-ui/react/overview.mdx
This PR makes some minor tweaks to the `@knocklabs/react` migration guide:
- call out provider API changes and CSS import updates
- make before/after code samples separate for readability
- use code samples from the feed implementation guide as examples for continuity between docs
> chore: expand react migration guide

- content/designing-workflows/channel-step.mdx
- content/guides/customizing-react-in-app-feed-components.mdx
- content/in-app-ui/react-native/notification-feeds.mdx
- content/in-app-ui/react/feed.mdx
- content/in-app-ui/react/reference.mdx
Updates some additional code examples that were using the react-notification-feed package or old version of the KnockFeedProvider
> chore: update react docs to reference @knocklabs/react

- content/integrations/email/layouts.mdx
Adds a callout in the email layout documentation to remind users that `<head>` and `<body>` are included in the **layout** and should not be added to the **template** when transferring a template from an outside provider. Adding this to the documentation as this has come up twice in the last month when helping customers.
> Chore: Add callout regarding transferring email templates

- content/in-app-ui/javascript/overview.mdx
The GitHub links on the "Building in-app UI in Javascript" page in the docs were still pointing to https://github.com/knocklabs/knock-client-js which has been archived and moved to the new JS monorepo. This PR Is to update those links to point to the new location.
> Chore: Update GitHub links on JS SDK page

- content/developer-tools/integrating-into-cicd.mdx
- content/developer-tools/knock-cli.mdx
- content/guides/cicd-with-the-knock-cli.mdx
- data/sidebar.ts
This PR adds a new guide on using the Knock CLI in your CI/CD pipeline. It also adds sidebar navigation for that guide, and a link from the main Knock CLI page back to this guide.
> chore: add CI/CD CLI guide

- content/cli.mdx
- content/concepts/translations.mdx
- content/concepts/workflows.mdx
- content/integrations/email/layouts.mdx
This PR closes some gaps in our current CLI documentation:
- It fixes some small issues with the documentation on Translations folder structure, including updating an incorrect CLI command and adding some additional context
- It adds folder structures for both Workflows and Layouts
- It adds an additional example `layout.json` file to demonstrate linking the `html` and `text` sources from within a given Layout's folder when working with these resources locally
- It adds backlinks from the CLI reference to the folder structures referenced on the above resource pages
- It also adds a link back to the new CI/CD automation guide (#385) in each of the relevant sections
> chore: add folder structures to documentation for working with the CLI

- content/concepts/workflows.mdx
Per recent discussions, I've expanded a bit on our recommendations under "Thinking in workflows."
Also removed a superfluous word and fixed spacing in a callout block on the same page.
> chore: update "Thinking in workflows" to recommend more-strongly against complex workflows

- components/CodeBlock.tsx
- content/developer-tools/integrating-into-cicd.mdx
This PR does two things:
- Change all references of `yml` -> `yaml` to reflect the accepted convention
- Import YAML as one of the available languages for `react-syntax-highlighter` so that adding `yaml` to a markdown code block actually does something 😃
> chore: add yaml syntax highlighting

- content/in-app-ui/react-native/reference.mdx
- content/in-app-ui/react/reference.mdx
Docs updates for https://github.com/knocklabs/docs/pull/391 as that PR proposes removing date-fns locales and relying only on built-in browser localization using the `Intl` module.
> chore: remove dateFnsLocale params

- content/developer-tools/outbound-webhooks/event-types.mdx
- content/developer-tools/outbound-webhooks/overview.mdx
- data/sidebar.ts
- next.config.js
- Adds all the new control webhook types into the docs
- Breaks out a new event types page for all of the supported webhook event types
> feat: update webhook docs to include control content types

- content/developer-tools/outbound-webhooks/event-types.mdx
- content/developer-tools/outbound-webhooks/overview.mdx
This PR adds a few search tags to the new documentation for outbound webhooks.
> chore: add tags to new webhook docs

- content/send-notifications/message-statuses.mdx
This PR updates the delivery status documentation to clarify that you cannot update a push notification's delivery status, but you _can_ update the engagement status manually by using the `knock_message_id`.
> fix: clarify push notification status updates

- content/in-app-ui/javascript/quick-start.mdx
- content/in-app-ui/react/feed.mdx
Adds examples showing how to use the socket manager in the JS SDK and React SDK
> chore: add examples for the socket manager

- content/concepts/commits.mdx
- content/concepts/environments.mdx
- content/concepts/overview.mdx
- content/concepts/workflows.mdx
- data/sidebar.ts
This PR updates the Environments concept page in our docs and moves the concepts of Commits and Promotion to a separate page. The changes include:
- Rearrange the order of some content to make it clearer
- Add additional search tags
- Add a new section on commit diffs (including a gif asset)
- Add explicit instructions on how to take certain actions in your dashboard, and mention the ability to perform these same actions via the MAPI or CLI
- Add Commits to sidebar nav
- Add Commits to the Concepts overview page, re-order the concepts on the overview page to match the nav ordering, and add a section for Recipients, which was missing
- Update the Workflows concept page's backlinks to separate version control and environments
> chore: update documentation for commits and promotion 

- content/guides/filtering-in-app-feeds.mdx
We misspelled "recipients" in a couple spots on this page.
> fix: typos in code examples for feed filtering

- content/concepts/schedules.mdx
Updates the anchor tag for non-recurring schedules to the correct header.
> Fix: Update non-recurring schedules anchor tag

- content/in-app-ui/flutter/overview.mdx
> fix: typo on flutter page

- content/integrations/chat/slack/overview.mdx
Updates the overview for Slack.
[KNO-5353](https://linear.app/knock/issue/KNO-5353/docs-update)
> fix(kno-5353): update slack overview

- content/in-app-ui/javascript/quick-start.mdx
- content/in-app-ui/javascript/reference.mdx
Fix a few outdated references to `knockClient.listenForUpdates` return type
> fix: update teardown refs for client

- content/integrations/sources/segment.mdx
- data/code/sources/eventPayload.ts
Removing callout that you need to append "data." in place of "properties." to access variables that live within "properties" object of a segment track event. 
I just tested this and if you use `properties.` instead of `data.` it still works as expected, so I think we should remove this callout that you need to prefix properties with `data.` to use them in event action mappings. 
Here's a Loom of me testing this if you want to confirm: https://www.loom.com/share/e7dab22258f44ea996d2bad4089dc231
> Remove data prefix callout from segment doc

- content/in-app-ui/react/reference.mdx
Documentation for the `onAuthenticationComplete` callback
[KNO-5428](https://linear.app/knock/issue/KNO-5428/onauthenticationcomplete-docs)
> feat(kno-5428): add docs for onAuthenticationComplete

- content/reference.mdx
Clarifies in the documentation that the max limit for the `page_size` query param for feed requests is 200.
> Chore: Add max limit to page_size for feed

- data/code/tenants/set.ts
A customer reported an issue with the way we document the Golang example for setting a tenant [in the API reference](https://docs.knock.app/reference#set-tenant). This PR resolves the issue.
> fix: update Go code example for setting a tenant

- data/code/tenants/set.ts
The `knock-ruby` SDK has a [required keyword argument](https://github.com/knocklabs/knock-ruby/blob/main/lib/knock/tenants.rb#L48) `tenant_data` for the `Tenants.set()` function. This PR updates the example usage.
> fix: use required keyword arg naming for ruby set tenant example

- content/sdks/react/reference.mdx
Adds a reference section for `renderHeader` to the `NotificationFeed` for header overrides
> add renderHeader reference

- content/concepts/tenants.mdx
- content/in-app-ui/react/slack-kit.mdx
- content/integrations/chat/slack-kit/overview.mdx
- content/integrations/chat/slack-kit/setup.mdx
@meryldakin @JEverhart383 ahead of SlackKit's big day next week started a quick PR of final docs clean up based on beta feedback doc in notion here: https://www.notion.so/knockapp/SlackKit-beta-feedback-a33859a547944653ad09492892f39b7b
**done**
- cleaning up some formatting stuff on react slackkit page
- added in some links to other parts of docs where helpful
**remaining:**
- some of code examples at bottom of doc could use clean up on indentation etc
- looks like we aren't able to pass titles to code components for some reason but think those would help a lot especially in full sample code section where there a bunch of code samples one after the other. as a new reader to those found it a bit hard to understand what i was looking at
> final slackkit doc updates

- data/code/users/merge.ts
The Java example for `merge` used the `identify` method instead.
> fix: example for Java merge

- content/reference.mdx
The List Subscriptions [endpoint](https://docs.knock.app/reference#list-subscriptions) can return all of the specified object's recipient subscribers, _or_ all of that object's subscriptions to other objects (as a recipient itself), depending on the provided `mode` parameter. There's some additional work to be done with the SDK methods to make this easier to understand (some discussion about that happened in the community slack [here](https://knockcustomers.slack.com/archives/C033CKE13SS/p1711066678839589)), but this should hopefully make it easier to understand in the meantime.
> chore: clarify list subscriptions mode parameter

- components/PageNav.tsx
This PR adjusts the height calculation of the `<aside>` menu component so that it never overlaps the footer.
https://www.loom.com/share/e371409be70c459f902a5b751ca9e5eb?sid=8f7a53b0-e4b6-4813-a3f5-4fa17d1d1e74
> fix: <aside> component height

- content/integrations/email/layouts.mdx
This PR adds a section on custom fonts in email layouts. In includes the proper way to import them and calls out the lack of support for custom fonts in many popular email clients.
> chore: add custom email font guidance

- content/concepts/environments.mdx
In response to some customer feedback, this PR adds a reference to our commit model (and relevant links) to the Environments concept page.
> chore: add reference to commit model to environments page

- components/PageNav.tsx
This PR should fix the persistent issue with `<aside>` height rendering that #444 was meant to fix; there appears to be some extra padding on the deployed version of the docs site that means that the version which looks correct locally does not look exactly the same when deployed.
I tested this by editing the component height directly in the browser to find the correct height calc. We should be able to take a look at the Vercel preview here to confirm that all looks good (I like to navigate to the "Preferences" page, then make sure my screen is both wide enough to render the `<aside>` element and short enough that it requires scrolling. Scroll all the way to the bottom to see whether the footer overlaps the "On this page" sidebar).
> fix: aside height render for deployed site

- content/reference.mdx
Update api docs to represent `recipients` and `objects` filtering as a map of maps. For recipients, both list and map structures are accepted
Ticker [KNO-5632](https://linear.app/knock/issue/KNO-5632/[docs]-update-objects-and-recipients-support-for)
> chore(kno-5632): update api docs with recipients and objects filtering

- components/Step.tsx
- content/getting-started/quick-start.mdx
Adds a new `titleSize` prop to `Steps` and `Step` component that will render h2, h3, or p tags (default). Using `h2` or `h3` means the jump nav will be rendered.
> chore: add titlesize to steps component

- content/integrations/chat/slack-kit/setup.mdx
This PR adds the new Step and Accordion components to the SlackKit setup page to organize things better. It also makes a few copy edits for clarity and grammar, and removes `code` styling from non-code references.
https://docs-o4ex5sir5-knocklabs.vercel.app/integrations/chat/slack-kit/setup
> chore: add new components to slackkit setup

- content/reference.mdx
Add context on a common reason for the `invalid_channel` error.
> chore: clarify reason for channel_invalid error

- content/integrations/chat/discord.mdx
- content/integrations/chat/slack-diy/building-oauth-flow.mdx
This PR adds a callout block to help a user understand what the Knock `channel_id` is and where to find it for a Discord channel (similar to the callout for setting channel data for Slack). This is in response to customer confusion on what this ID represents.
> chore: add callout on finding channel id for Discord

- content/concepts/channels.mdx
- content/concepts/recipients.mdx
- content/concepts/schedules.mdx
- content/concepts/subscriptions.mdx
- content/concepts/tenants.mdx
- content/concepts/users.mdx
- content/concepts/workflows.mdx
- content/designing-workflows/batch-function.mdx
- content/designing-workflows/branch-function.mdx
- content/designing-workflows/delay-function.mdx
- content/designing-workflows/throttle-function.mdx
- content/developer-tools/api-keys.mdx
- content/developer-tools/api-logs.mdx
- content/developer-tools/service-tokens.mdx
- content/guides/customer-webhooks.mdx
- content/in-app-ui/overview.mdx
- content/integrations/sources/http.mdx
- content/integrations/webhook/overview.mdx
- content/manage-your-account/audit-logs.mdx
- content/managing-recipients/deleting-users.mdx
This PR places all of our "Frequently asked questions" into accordion groups. It also makes fixes for typos and outdated information ("trigger conditions," anyone?) that I found along the way.
Apologies for the massive PR, it got bigger than I expected and I was already too deep 😅 
**Note:** For FAQs that had only a single question, I opted to default the accordion to "open".
> chore: add accordion groups to all FAQ sections

- content/integrations/sources/http.mdx
This PR adds an FAQ callout to the generic HTTP source page to clarify that you can use inline identification with that source (and how to do it).
> chore: add faq about inline identification for generic http source

- components/Card.tsx
- components/SdkCard.tsx
Adds the option to open a card component's link in a new tab.
https://www.loom.com/share/cc6ab01d1fd14c11ae90e32ba30c285e?sid=f40e8424-d220-44d1-99c2-c5fa21f831bf
> chore: add support to open card links in new tab

- components/SdkCard.tsx
- content/getting-started/example-app.mdx
- content/getting-started/what-is-knock.mdx
- content/sdks/overview.mdx
- package.json
- yarn.lock
This PR does a few things related to the `SdkCard` component:
- makes the SDK Card a bit more flexible so you can choose your own icon for the card
- bumps the version of `react-icons` to allow for import of all the relevant icons
- imports a bunch of icons for our various SDKs and example apps and adds them to a typed list of supported icons
- adds `icon` props to all of the currently-existing SDK cards for which they were relevant
- adds the `isExternal` prop to all cards that have external links so that they'll open in a new tab
> chore: sdk card improvements

- components/Endpoints.tsx
This PR fixes a UI bug in the `Endpoints` component which was allowing endpoints that exceeded a certain character length to overflow their container. The update adds a horizontal scroll bar for endpoints that are too long (mimicking the code block components) and a bit of margin on the endpoints themselves so the scrollable section has equal padding on either side.
See https://docs-git-mk-endpoints-component-knocklabs.vercel.app/reference#channel-data for an example
> fix: prevent `Endpoints` from overflowing container

- content/concepts/translations.mdx
Includes information on using the t tag for translations.
[KNO-5590](https://linear.app/knock/issue/KNO-5590/t-tag-documentation)
> add t tag info to translations concept

- content/integrations/overview.md
- next.config.js
This PR does a few things:
1. changes 302 redirects to 301 from the recent 'Getting Started' updates
2. Adds redirects for any not-found URLs that appeared in the GA 404 report
3. Updates one link on integrations page
> chore: address 404s 

- content/sdks/javascript/reference.mdx
clarifies an existing note on the `fetchNextPage` method on the JS reference
> chore: clarify note on fetchNextPage

- content/concepts/channels.mdx
- content/concepts/environments.mdx
- content/concepts/preferences.mdx
- content/concepts/subscriptions.mdx
- content/concepts/variables.mdx
- content/concepts/workflows.mdx
- content/designing-workflows/batch-function.mdx
- content/designing-workflows/channel-step.mdx
- content/designing-workflows/delay-function.mdx
- content/developer-tools/api-keys.mdx
- content/developer-tools/api-logs.mdx
- content/guides/building-recurring-digests.mdx
- content/in-app-ui/react/custom-notifications-ui.mdx
- content/in-app-ui/react/feed.mdx
- content/in-app-ui/react/inbox.mdx
- content/in-app-ui/react/toasts.mdx
- content/in-app-ui/security-and-authentication.mdx
- content/integrations/chat/discord.mdx
- content/integrations/chat/slack-diy/building-oauth-flow.mdx
- content/integrations/email/aws-ses.mdx
- content/integrations/email/layouts.mdx
- content/integrations/overview.md
The main thrust of this PR is to update mentions of navigating in the dashboard to be consistent in their styling: 
- a **Page** in the dashboard is bolded, and a series of page navigations will look like **Page One** > **Page Two**
- a "Button" label (or other clickable entity) will have quotes 
Along the way, I'm also fixing information which is outdated or no longer fully accurate. Examples:
- We changed the way that Variables are set (they now live in **Settings** rather than under the **Developers** menu)
- Related to the above, you no longer need to switch environments to change environment-level variable overrides (all of your environments are listed under each variable). Because of this, I removed the mention of Variables from the Environments concept page altogether (it was …
> chore: update dashboard navigation instructions (part 1)

- content/integrations/extensions/data-sync.mdx
Adds an example of what the table definitions from Prequel are for customers to be able to review prior to completing the setup via the magic link. It also fixes a breadcrumb issue on the `/data-sync` page.
https://docs-git-rt-add-schema-definitions-knocklabs.vercel.app/integrations/extensions/data-sync
Let me know if there's any information I should exclude from the example (i.e., varying lengths)
> chore: add example table definition

- components/CodeBlock.tsx
- components/MultiLangCodeBlock.tsx
- content/playground.mdx
- data/code/workflows/playground.ts
In preparation for adding `cURL` and mobile SDK examples to some of our multi-language code block examples (in the API ref), this PR does several things:
- register `cURL`, Kotlin, and Swift as `SupportedLanguages`
- refactor `MultiLanguageCodeBlock` to base the list of languages in the switcher on the examples in the given code `snippet`, ordered by a `DEFAULT_ORDER`
- add additional logic to the rendered `code` so that if a given code block does not include an example for the language that is currently stored in `localstorage`, we will still render the correct code to match the language that is displayed on the switcher (which will always be the first language in the list).
For example: if you switch a block to `cURL` and `"curl"` is subsequently set in local storage, with the current …
> chore: add support for dynamic language list on multilang code block

- content/reference.mdx
Adds info about the limit of the number of recipients you can subscribe to an object with each request (this is specified [here](https://docs.knock.app/concepts/subscriptions#subscribing-recipients-to-an-object), but adding it to the API docs for increased visibility).
https://docs-git-rt-add-recipient-limit-api-docs-knocklabs.vercel.app/reference#add-subscriptions
> chore: include recipient limit on adding subscriptions

- content/in-app-ui/react/custom-notifications-ui.mdx
- content/sdks/react/reference.mdx
Updates the reference entry from `useKnock` to `useKnockClient` and updates the headless UI implementation guide to use that pattern while we investigate strange behavior with `useAuthenticatedKnockClient`
> chore: update reference, guide for useKnockClient

- data/code/api/idempotency.ts
- data/code/workflows/cancel-with-recipients.ts
- data/code/workflows/trigger-with-actor.ts
- data/code/workflows/trigger-with-attachment.ts
- data/code/workflows/trigger-with-branding-tenant.ts
- data/code/workflows/trigger-with-identification.ts
- data/code/workflows/trigger-with-object-as-actor.ts
- data/code/workflows/trigger-with-object-as-recipient.ts
- data/code/workflows/trigger-with-object-identification.ts
- data/code/workflows/trigger-with-tenant.ts
- data/code/workflows/trigger-with-user-channel-data.ts
- data/code/workflows/trigger-with-user-identification.ts
- data/code/workflows/trigger-with-user-preferences.ts
- data/code/workflows/trigger.ts
Brings the docs improvements from the go sdk readme into our docs site (https://github.com/knocklabs/knock-go/pull/33)
Also fixes some other compilation errors in our go docs snippets. Most of my focus in this PR was on snippets related to workflow triggering, we should also audit the remaining go snippets.
> Fix bugs in Go docs snippets

- data/code/workflows/cancel-with-recipients.ts
- data/code/workflows/trigger-with-actor.ts
- data/code/workflows/trigger-with-attachment.ts
- data/code/workflows/trigger-with-branding-tenant.ts
- data/code/workflows/trigger-with-identification.ts
- data/code/workflows/trigger-with-user-channel-data.ts
- data/code/workflows/trigger-with-user-identification.ts
- data/code/workflows/trigger-with-user-preferences.ts
- data/code/workflows/trigger.ts
Matt [spotted a bug in my previous PR](https://github.com/knocklabs/docs/pull/507/files#r1604009207). I've decided to change all instances of `req` to `request` for consistency in our Go snippets.
> fix: refactor req -> request in go snippets

- content/reference.mdx
Explicitly call out need for `PreferenceSet` id to be `default` or `tenant.id` in a few additional places in the API ref
> chore: callout prefs ids in a few additional places

- content/concepts/objects.mdx
This PR updates the Objects concept page to make it clearer that support for an Object recipient of an in-app feed is not currently available but on the roadmap. Current state seems to indicate that it's possible in the list, and only mentions that it isn't yet available in the roadmap callout below.
> chore: clarify current lack of support for Object feeds

- content/managing-recipients/identifying-recipients.mdx
- content/reference.mdx
This PR is meant to coincide with the update being made on KNO-5942. For the most part, the current state of the docs actually describe updated behavior (we didn't call out the currently-existing caveat for inline identification, where we do not upsert recipients that contain only an `id` when identified via that method), so there weren't many changes to make. However, I did add a callout of what can occur when a given recipient doesn't have the necessary properties to allow us to deliver a notification.
Also fixed one broken and one outdated link in the API ref.
> chore: update docs for new inline identify behavior

- content/reference.mdx
Adds missing description for `:id` path parameter on `GET /users/:id/subscriptions` endpoint
> fix: add missing path param for get user subscriptions

- content/managing-recipients/identifying-recipients.mdx
User called out a 404 with this link, looks like it's pointing to an old page in the same section that should have been redirected, so just removed it
> fix: remove 404 link

- content/concepts/translations.mdx
- content/mapi.mdx
A refresh on translations docs as we add support for t tags. 
@connorlindsey A couple questions: 
* Do we need to call out PO files in here in some way? 
* On code example under "Commit your workflow", it looks like we're using autogenerated id for translation key but I believe this should be the translation string itself?
> Sts translations refresh

- components/CodeBlock.tsx
- components/MultiLangCodeBlock.tsx
This PR add's support for `jsweb` examples in a multilang block (for any client-side JS SDK examples).
> chore: add support for JS client-side SDK in multilang block

- components/SdkCard.tsx
- content/concepts/translations.mdx
This adds a new icon option to the SDK card and uses it to call out videos where we have them. I think embedding most videos it too disruptive, but in some cases where the concept is complex a link might not be suggestive enough, so this is a nice-looking middle ground. 
Open to feedback here though cause it's still somewhat in your face
> feature: add video and card

- components/SupportModal.tsx
- content/concepts/translations.mdx
- content/integrations/sources/rudderstack.mdx
- next.config.js
- package.json
- pages/_app.tsx
- yarn.lock
- Hot reloads docs when editing content in the `/content` folder
- Fixes a hydration error on the translations page caused by nested anchor tags. I clicked through every page and didn't see any other hydration errors pop up. 
- Fixes an issue with the support overlay where the sidebar was rendering on top of the overlay where it should be behind it. 
[KNO-6060](https://linear.app/knock/issue/KNO-6060/%5Bdocs%5D-fix-hydration-errors-when-editing-docs-locally)
> fix: hot reloading and hydration errors when editing docs locally

- components/Card.tsx
Extends the "clickable" area of the `Card` component to the edge of the card. Right now, the padding is between the "link" area and the border of the card, so you can hover on the edge of the button and not be able to click it.
Old: https://docs.knock.app/sdks/overview
New: https://docs-git-mk-sdk-card-click-area-knocklabs.vercel.app/sdks/overview
> chore: extend clickable link area to full card size

- content/send-notifications/message-statuses.mdx
- content/send-notifications/tracking.mdx
Add "webhook" to various places where we call out support for different types of channels
[Link & open tracking](https://docs-git-mk-webhook-channel-mentions-knocklabs.vercel.app/send-notifications/tracking)
[Message statuses](https://docs-git-mk-webhook-channel-mentions-knocklabs.vercel.app/send-notifications/message-statuses)
> chore: add webhook channel to various mentions of supported channels

- data/code/tenants/set.ts
Changes `data` to `tenant_data` for the `set_tenant` function to align with what is required ([SDK def](https://github.com/knocklabs/knock-python/blob/2c54be2de1cd37e26816a07d46fa82e75cd91e3d/knockapi/resources/tenants.py#L32)).
https://docs-git-rt-python-set-tenant-fix-knocklabs.vercel.app/concepts/tenants#syncing-tenant-data-to-knock
> Fix: update argument name for Python set_tenant example

- content/in-app-ui/api-overview.mdx
- content/in-app-ui/react/feed.mdx
- content/sdks/react/reference.mdx
- Adds reference for types for new block types
- Removes inline actions callout
- Adds reference for new `onNotificationButtonClick` events
KNO-6136
> chore: add docs for new actionable in-app notifs

- content/in-app-ui/react/preferences.mdx
Adds a video card to the preferences quickstart page
> chore: add video card to quickstart

- content/send-notifications/triggering-workflows.mdx
From our conversation during the DSE/Dev Rel sync last week, searching "actor" in the docs only yields results for the Users concept page. I'm adding an "actor" tag for the Triggering Workflows page, as that page contains the most helpful explanation of what an actor is and when it can be used: https://docs-git-rt-add-actor-tag-triggering-workflows-knocklabs.vercel.app/send-notifications/triggering-workflows#attributing-the-action-to-a-user-or-object 
This is a short-term fix, but I think it adds to the argument for having a glossary page in Docs 2.0.
> chore: add actor tag to triggering workflows page

- content/in-app-ui/react/toasts.mdx
A user in Slack pointed out that the previous example renders the block content as an HTML string, which is the default behavior of the lib, so I made this example use `toast.custom` function to actually render the HTML of the in-app template
> fix: update toast code example

- content/reference.mdx
> fix: typo on `message_ids` filter

- content/reference.mdx
Two more instances of `messge` instead of `message`
> fix: typos in API ref

- content/reference.mdx
- data/apiReferenceSidebar.ts
This PR documents the new `GET /v1/messages/batch/content` endpoint added in [#2511](https://github.com/knocklabs/switchboard/pull/2511).
https://docs-15ps0u3mn-knocklabs.vercel.app/reference#batch-get-message-content
> chore: document batch message content endpoint

- content/manage-your-account/authentication-methods.mdx
SAML 2.0 SSO is only available on Enterprise-level plans.
> fix: remove growth plan from SAML 2.0 SSO documentation

- content/integrations/email/sendgrid.mdx
Document the `knock_recipient_id` custom arg that we send to Sendgrid.
> chore: add info about custom args to sendgrid docs

- content/concepts/schedules.mdx
- content/reference.mdx
- Add the `scheduled_at` parameter to the API reference for Schedules ([here](https://docs-git-mk-update-schedules-knocklabs.vercel.app/reference#create-schedules) and [here](https://docs-git-mk-update-schedules-knocklabs.vercel.app/reference#update-schedules))
- Clarify that the `scheduled_at` timestamp must be a UTC datetime in ISO-8601 format ([here](https://docs-git-mk-update-schedules-knocklabs.vercel.app/concepts/schedules#schedule-properties))
> chore: add `scheduled_at` to Schedules reference

- content/concepts/recipients.mdx
Found a broken link while perusing the inline identify docs for Recipients.
KNO-6356
> fix(KNO-6356): fix recipient inline identify broken link

- content/concepts/recipients.mdx
Fixes typo that is resulting in a 404. Confirmed fix with preview URL by going to https://docs-git-rt-fix-inline-identify-404-knocklabs.vercel.app/concepts/recipients#recipientidentifier-definiton and clicking on the "identified inline" hyperlink.
> fix(KNO-6369): fix typo for inline identify link

- content/send-notifications/triggering-workflows.mdx
This PR updates the list of effects of including an `actor` on a trigger to include the fact that an `actor` is never notified as a `recipient`. Right now, this information is rather buried in the Subscriptions FAQ.
https://docs-a86l84q42-knocklabs.vercel.app/send-notifications/triggering-workflows#attributing-the-action-to-a-user-or-object
> chore: add info about actor being excluded from recipients

- content/designing-workflows/fetch-function.mdx
Updates the fetch function docs to add information regarding specifying the response path.
FYI - I opted to leave the "Merge data" section as is since I believe that is still the default behavior, but let me know if we think this should be reworked 👍
> Chore: add info for specifying the response path on fetch steps

- content/manage-your-account/roles-and-permissions.mdx
Adds a callout to the roles and permissions page about customizing promotion permissions being an enterprise feature that interested customers can contact our sales team about to learn more:
https://docs-git-rt-add-enterprise-promotion-callout-knocklabs.vercel.app/manage-your-account/roles-and-permissions
> Chore: add callout for customizing promotion permissions

- content/developer-tools/outbound-webhooks/event-types.mdx
Add `message.interacted` to the list of available outbound webhook events.
https://docs-fnjtf7ixc-knocklabs.vercel.app/developer-tools/outbound-webhooks/event-types#messageinteracted
> chore: add `message.interacted` webhook event

- content/developer-tools/outbound-webhooks/event-types.mdx
We currently list the extra `EventData` param that is included with a `message.link_clicked` event incorrectly. It should be a `url`, not `link_clicked`.
https://docs-fmj18zbrl-knocklabs.vercel.app/developer-tools/outbound-webhooks/event-types#messagelink_clicked
I checked this in the codebase and also confirmed with a webhook test:
```
{
.... 
"event_data": {
"__typename": "EventData",
"url": "https://www.google.com"
},
"type": "message.link_clicked"
}
```
> fix: correct EventData attributes for a `message.link_clicked` event

- content/guides/going-to-production.mdx
- content/guides/migrate-from-courier.mdx
- data/sidebar.ts
This PR introduces a new Guide on migrating from Courier to Knock. It includes the relevant navigation update, and also updates the `section` on the "Moving to production" guide that was previously moved in the nav but not updated.
In addition to review of written content, it would be helpful to get feedback (if any) on any potential visual improvements as well.
https://docs-yg1ymevhd-knocklabs.vercel.app/guides/migrate-from-courier
> chore: add courier migration guide

- content/integrations/sources/overview.mdx
- content/reference.mdx
- content/send-notifications/triggering-workflows.mdx
- Updates text for the triggering workflows guide
- Adds a note to source events guide
- Updates the API reference to note the limit
[KNO-6483 : \[Docs\] Fill in docs gaps for the 1k recipient per trigger limit](https://linear.app/knock/issue/KNO-6483/[docs]-fill-in-docs-gaps-for-the-1k-recipient-per-trigger-limit)
> feat(kno-5483): update docs on the 1k recipient limit

- content/concepts/subscriptions.mdx
- content/send-notifications/triggering-workflows.mdx
This PR clarifies current behavior around the `actor` on a workflow: the exclusion of an `actor` from the list of a workflow's `recipients` will only occur for the Subscriptions use case.
- https://docs-huooueii7-knocklabs.vercel.app/send-notifications/triggering-workflows#attributing-the-action-to-a-user-or-object
- https://docs-huooueii7-knocklabs.vercel.app/concepts/subscriptions#frequently-asked-questions
> fix: update actor documentation to reflect current behavior

- content/reference.mdx
This PR updates the Tenants portion of the API reference for accuracy:
- Adds `entries` and `page_info` keys to account for pagination on the "List tenants" endpoint
- Adds `preference_set` to the description for the `settings` attribute and to the example responses
https://docs-oknin15lr-knocklabs.vercel.app/reference#tenants
> chore: update tenant return values for accuracy

- content/reference.mdx
- data/apiReferenceSidebar.ts
Currently, the API reference sidebar and page content are out of alignment. This PR:
- Re-orders the sidebar to put most-trafficked topics higher up and group similar topics near each other (discussion on ordering decision [here](https://knocklabs.slack.com/archives/C068SUY4C06/p1721854907644659))
- Re-orders the content on the actual page to align with the sidebar order
- adds the "Remove message status" endpoint to the sidebar nav (it was previously unlisted there)
https://docs-jyou09ery-knocklabs.vercel.app/reference
> chore: re-order api ref sidebar and content to align. add missing endpoint.

- content/developer-tools/api-logs.mdx
Tells users when and why we truncate logs. I didn't add specific numbers on what size we truncate at, but we can if we think that would be helpful. 
[kno-6592](https://linear.app/knock/issue/KNO-6592/[docs]-docs-on-log-truncation)
> chore(kno-6592): add docs on log truncation

- content/sdks/javascript/reference.mdx
Documents `markAsInteracted` from the [JS SDK](https://github.com/knocklabs/javascript/blob/bacf030f43a5d8cd1c17c88c672188c4a17808dd/packages/client/src/clients/feed/feed.ts#L289) 
https://docs-jq4zc2g9s-knocklabs.vercel.app/sdks/javascript/reference#markasinteracted
> chore: add markAsInteracted to JS SDK reference

- content/integrations/webhook/overview.mdx
Adds some clarification to the override webhook configurations section: https://docs-git-rt-clarify-webhook-channel-override-knocklabs.vercel.app/integrations/webhook/overview#overriding-webhook-configurations
I opted to not use a callout. Here is the version I went with:
Here is it with a callout (it looked awkward to just callout "these overrides apply to all environments where the step is promoted":
Also, I noticed that this page has a lot of "Note:" throughout. I'm going to work on cleaning that up in a separate PR, and update anything that feels as though it should be a callout to use the `<Callout>` component.
> chore: update description for override webhook configurations

- content/integrations/webhook/overview.mdx
Updates the **Notes:** on the webhook overview page to use the `<Callout>` component instead to draw the user's attention better.  
https://docs-git-rt-clean-up-webhook-notes-knocklabs.vercel.app/integrations/webhook/overview
> chore: update notes on webhook page to use the callout component

- content/designing-workflows/template-editor/overview.mdx
Fixes a sentence fragment about email layouts and adds it to a callout with a link to what a Layout is.
https://docs-63g33dvaf-knocklabs.vercel.app/designing-workflows/template-editor/overview#previewing-and-testing-your-notification-template
> fix: sentence fragment about email layouts

- content/in-app-ui/react/preferences.mdx
This PR updates the code examples on the React preference center example to add a conditional check on whether the `preferenceKey` exists. This should resolve the TS errors reported by a customer [here](https://github.com/knocklabs/javascript/issues/153).
> chore: update conditions on existing preference check

- content/concepts/schedules.mdx
- content/concepts/subscriptions.mdx
Adding a callout to the schedules concept page about listing an object as a recipient of the schedule will not fan out to subscribers of that object. Also adds an FAQ item to the subscriptions page addressing this.
> chore: add callout and FAQ to docs regarding scheduled subscriptions

- content/integrations/push/expo.mdx
This PR does two things:
1. Update link under payload override section to reference Expo's notification send API docs rather than the client-side `NotificationContent` (not all of the front-end params are supported by Expo API).
2. Update all Expo links to use `<a>` tags that open in a new tab rather than redirecting away from Knock documentation.
https://docs-nopm4mqaq-knocklabs.vercel.app/integrations/push/expo
> chore: update expo links

- content/concepts/subscriptions.mdx
Changes `removeSubscriptions` to `deleteSubscriptions` and updates the title of that codeblock
> chore: update method and title

- content/reference.mdx
Our `Endpoint` component has a `withLink` prop that allows a given listed endpoint to link to the place in the reference where it is documented.
We apply `withLink` inconsistently right now; it's only used in a few sections on the reference, but it's actually very convenient if you're looking at the "Overview" of any of the sidebar sections.
This PR:
- adds `withLink` where it was missing
- corrects some links that were broken because the `name` on the endpoint didn't match the anchor tag for the relevant documentation
- updates the way that we reference the path parameter for loading an in-app feed (we use `:feed_id` in most places but also referenced `:in_app_feed_channel_id` in a few spots).
- removes the internal-use `GET /users/:user_id/feeds/:feed_id/settings` endpoint that was …
> fix: correct broken links and add links to endpoints in reference "overview" sections

- components/MultiLangCodeBlock.tsx
- content/reference.mdx
- data/apiReferenceSidebar.ts
- data/code/objects/get-preferences.ts
- data/code/objects/list-preferences.ts
- data/code/users/get-preferences.ts
- data/code/users/list-preferences.ts
This PR adds documentation for the endpoints to list User and Object preferences. This includes:
- New code examples for these two endpoints
- Corrections to the existing "Get preferences" code examples (some were using the wrong methods, etc.)
- Modifications to the existing "Get preferences" code examples to make usage related to "default" preferences clearer
- Re-ordering the Preferences endpoints and sidebar 
https://docs-fl95gty42-knocklabs.vercel.app/reference#get-all-preferences-user
https://docs-fl95gty42-knocklabs.vercel.app/reference#get-all-preferences-object
> chore: add list preferences endpoints

- components/CodeBlock.tsx
This PR adds explicit styles for line numbers to our code blocks, as the default styling provided by the syntax highlighter doesn't seem to always be consistent across various code examples. You can check out the looms below to see what the issue looks like right now.
I just grabbed the styles as they were rendered on the page in one of the examples that looked "correct," but we can modify them to have a bit more left margin etc. if desired.
Example endpoint that I show in the videos: https://docs-bs9b7rmx6-knocklabs.vercel.app/reference#get-message-activities
https://www.loom.com/share/fe188131c51345f7a34f091d6aba20eb
https://www.loom.com/share/75f5a7e8bc7442519bfbbed251ae7980
> fix: consistent line number styling

- components/CodeBlock.tsx
- content/in-app-ui/react-native/components.mdx
- content/in-app-ui/react-native/customization.mdx
- content/in-app-ui/react-native/notification-feeds.mdx
I noticed that the newly added code block examples for RN components didn't have the syntax highlighting applied, so I added tsx to be registered with the `SyntaxHighlighter`. I also made some small adjustments for some little things I found (i.e., added a line break between the code blocks).
> fix: add tsx language registration for SyntaxHighlighter

- content/reference.mdx
This PR adds a typeSlug link for `RecipientIdentifier` types in the API reference
> chore: add type links for recipientidentifier

- content/developer-tools/validating-trigger-data.mdx
- content/send-notifications/triggering-workflows.mdx
- data/sidebar.ts
Moves validating workflow trigger data into its own page under the developer tools section.
New page: https://docs-git-rt-move-trigger-validation-knocklabs.vercel.app/developer-tools/validating-trigger-data
Added a callout under the passing data section of the triggering workflows page: https://docs-git-rt-move-trigger-validation-knocklabs.vercel.app/send-notifications/triggering-workflows#passing-data#passing-data
> chore: create trigger data validation page

- content/mapi.mdx
This PR adds fields for workflow trigger validation, commit `sha`, and workflow frequency to the example workflow definition in the MAPI
https://docs-no0a8ced6-knocklabs.vercel.app/mapi#workflows-object
> chore: add trigger validation and frequency to workflow definition

- content/mapi.mdx
- layouts/MapiReferenceLayout.tsx
This PR does a few things to improve formatting of the mAPI reference:
1. Use the `<Section>` component where we had `<div>` tags to improve spacing and ensure consistency with the content columns
2. Add the various sub-definitions of Workflows into their own section in the sidebar menu to make them navigable and easier to find
3. Link all of the Knock `Types` in various `<Attribute>` components to their definitions
https://docs-a6x3z4evv-knocklabs.vercel.app/mapi
I noticed that the list of pages under "Workflow definitions" doesn't open and highlight the "active" page as expected, which I think is because the component really intends for these to be separate pages under a shared `/path`. I'm looking into that, but if it's something quick that someone else is already aware of re: the way …
> chore: fix mapi formatting

- content/designing-workflows/template-editor/variables.mdx
Fix formatting of template variables table (it got messed up in [latest update](https://docs.knock.app/designing-workflows/template-editor/variables))
> fix: formatting on template variables table

- content/mapi.mdx
This PR makes the following updates to the MAPI reference:
- Add attributes on the `Workflow` definition for `sha`, `trigger_frequency`, and `trigger_data_json_schema`
- Add a `conditions` object to the example workflow object
- Update some non-typed `object` references to their defined `Types`
- Add `typeSlug` links with additional context to many attributes throughout the reference, in order to link back to their definitions
https://docs-9pc4eysuz-knocklabs.vercel.app/mapi
I used the `typeSlug` to link a few things (like the `conditions` and `trigger_data_json_schema`) back to their definitions, even though they aren't "typed" per se; they're just an `object`. I think this is an acceptable use for it since it takes you to the place where you can learn more about the expected format of …
> chore: update mapi reference

- content/mapi.mdx
- layouts/MapiReferenceLayout.tsx
This PR adds a `ChannelSettings` type to the mAPI reference, so that it can be referenced in the `channel_overrides` attribute on a `ChannelStep`. It also links the attribute for push channel JSON overrides (which are at the template level) back to the place where its documented.
I also snuck in a mention of Partials at the top of the reference where we list the resources you can manage with mAPI.
**Note:** While both Push and Webhook channel types have `ChannelSettings` attributes in our product, they aren't currently relevant to `channel_overrides` and so I opted not to document them here. If we add endpoints to allow channel integration management via API at some point in the future, we'll want to add these other attributes so that we can reference the `ChannelSettings` type in those …
> chore: add channel overrides to mAPI

- content/getting-started/example-apps.mdx
Adds cards to the example apps page for Linear-style inbox and alerting examples
> feat: add new examples app cards

- content/in-app-ui/react/feed.mdx
looks like the formatting of these sections got messed up. It was like this:
But should be
> update code blocks

- components/SectionHeading.tsx
If the user clicks on a linked section heading within the API reference when the current URL already contains a `#` fragment, the URL in their browser bar will update to contain a second `#` fragment, which is invalid. (See _Before_ video included below.)
This bug occurs because `SectionHeading` gets the URL path from [the `asPath` string returned by the `useRouter` hook](https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object), which includes search params and fragments, and does not strip out any existing `#` fragment.
Instead of manually stripping out the `#` fragment, we can instead use the `usePathname` hook, which [returns the URL pathname without query params and fragments](https://nextjs.org/docs/app/api-reference/functions/use-pathname#returns).
The …
> fix(kno-6920): fix extra hash in links within API reference

- content/sdks/android/push-notifications.mdx
“Reveive” should be “receive”.
> fix: typo in Android SDK push notifications doc

- content/sdks/android/quick-start.mdx
- content/sdks/react-native/quick-start.mdx
Looks like these quick start docs reference the wrong push notification provider. This was probably a copy-and-paste mistake from [the iOS quick start docs](https://docs.knock.app/sdks/ios/quick-start).
> fix: push notification channels in RN and Android quick start docs

- content/in-app-ui/ios/overview.mdx
- content/in-app-ui/react-native/overview.mdx
- content/in-app-ui/react/customizing-feed-components.mdx
- content/in-app-ui/react/toasts.mdx
- content/integrations/push/apns.mdx
- content/integrations/push/one-signal.mdx
As per [Merriam-Webster](https://www.merriam-webster.com/dictionary/setup), “setup” is a noun and “set up” is a verb.
Forgive me for being a stickler. 🫠
> fix: "setup" should be "set up"

- content/developer-tools/api-logs.mdx
This PR adds additional information about log truncation to the docs (i.e. documenting `[TRUNCATED]` as well as adding an example). It also moves the mention that we don't log `/feeds` responses into a callout.
https://docs-git-mk-clarify-log-truncation-knocklabs.vercel.app/developer-tools/api-logs
> chore: add additional context on log truncation

- components/Attributes.tsx
- content/integrations/extensions/data-sync.mdx
- content/reference.mdx
- data/apiReferenceSidebar.ts
- Adds a top section to the reference on how Knock manages trigger data for filtering
- Updates endpoints that accept `trigger_data` filters to point to this reference
- Adds note on trigger data exported to warehouse connections
[PLA-443: Write docs on `searchable_trigger_data` filter usage + warehouse export](https://linear.app/knock/issue/PLA-443/write-docs-on-searchable-trigger-data-filter-usage-warehouse-export)
> feat(pla-443): add docs on trigger data filtering + warehouse export

- components/SdkCard.tsx
- content/in-app-ui/react-native/components.mdx
- content/in-app-ui/react-native/notification-feeds.mdx
- content/in-app-ui/react-native/overview.mdx
- content/sdks/expo/overview.mdx
- content/sdks/expo/push-notifications.mdx
- content/sdks/expo/reference.mdx
- content/sdks/overview.mdx
- content/sdks/react-native/overview.mdx
- content/sdks/react-native/push-notifications.mdx
- content/sdks/react-native/quick-start.mdx
- content/sdks/react-native/reference.mdx
- data/sidebar.ts
This PR updates the docs to include the Expo SDK added by knocklabs/javascript#243. I also updated the React Native push notifications guide to describe integrating push notifications using Firebase Cloud Messaging and React Native Firebase.
[KNO-7174](https://linear.app/knock/issue/KNO-7174/[expo-sdk]-update-docs-to-include-new-expo-sdk)
> feat(kno-7174): add Expo SDK docs

- content/sdks/android/push-notifications.mdx
The function should be named `onKnockPushNotificationTappedInBackground`, with a lowercase g, as per [the `KnockActivityInterface` interface](https://github.com/knocklabs/knock-android/blob/96707ada2ee0bec439364ef320d5a293e607915e/sdk/src/main/java/app/knock/client/KnockActivity.kt#L28).
> fix: KnockActivity code snippet in Android push docs

- components/PageNav.tsx
Right now, we only re-render the document headers if the page's `title` changes. This works in most situations, but we do have a few cases (i.e. https://docs.knock.app/concepts/preferences and https://docs.knock.app/preferences/overview, or https://docs.knock.app/designing-workflows/template-editor/variables and https://docs.knock.app/concepts/variables) where pages share a title, which means that we don't re-render the "On this page" sidebar.
This PR adds `sourcePath` to the `useEffect` so that we will re-render based on the path for the page changing as well.
To test, you can navigate between https://docs-6kbzcboux-knocklabs.vercel.app/concepts/preferences and https://docs-6kbzcboux-knocklabs.vercel.app/preferences/overview, or …
> fix: re-render `documentHeaders` on `sourcePath` change (KNO-7200)

- content/manage-your-account/managing-members.mdx
Add a clarification that it is for non-public domains for **_owners_** of the account (current text reads as if the domain options available are for any members of the account).
> chore: add auto-join clarification 

- content/getting-started/what-is-knock.mdx
- content/integrations/email/overview.mdx
- content/integrations/email/smtp.mdx
- content/integrations/overview.md
- data/integrationsSidebar.ts
This PR updates the docs to describe sending email via SMTP using Knock.
[KNO-7184](https://linear.app/knock/issue/KNO-7184/update-docs-to-include-smtp)
> feat(kno-7184): add SMTP docs

- content/sdks/react-native/overview.mdx
We previously received feedback that our docs don’t make it clear which versions of React Native our SDK can be used with. While we don’t currently test the SDK with multiple versions of React Native, we can at least mention that we test with React Native v0.73.4 internally.
> docs: mention version of React Native used to test SDK

- content/integrations/sources/overview.mdx
- content/integrations/sources/rudderstack.mdx
- content/integrations/sources/segment.mdx
Due to customer confusion, this PR explicitly calls out that the test runner will only work with existing users for source events (meaning inline identification is not supported). It also updates some outdated links and adds an additional link to the documentation of what inline identification is.
When you use the rest runner (which triggers a workflow run for the most-recently-saved version of a workflow rather than hitting our public API), we don't support inline identification. For API-triggered workflows, the test runner modal allows you to select from a list of existing users. However, a source event-triggered workflow allows you to simply paste in a test event (with any recipient(s) that you would like to test with), meaning that it's possible to use inline identification syntax in …
> chore: add callouts for inline identify with source events

- content/concepts/objects.mdx
- content/concepts/users.mdx
As per testing related to [this discussion](https://knocklabs.slack.com/archives/C01RLET7A6B/p1729898958187719), it appears that our documentation regarding the way that we merge recipient properties on subsequent upserts is outdated. We employ a deep merge strategy, which means that you can send updated values for nested properties without overwriting other values.
I'll hold off on merging these updates until we address [KNO-7239](https://linear.app/knock/issue/KNO-7239/[switchboard]-merging-properties-on-recipients-objectsuserstenants)
- Preview of [User update](https://docs-git-mk-merge-prop-update-knocklabs.vercel.app/concepts/users#storing-user-properties)
- Preview of [Objects update](https://docs-git-mk-merge-prop-update-knocklabs.vercel.app/concepts/objects#properties)
> chore: update descriptions of merge behavior

- content/integrations/extensions/data-sync.mdx
- content/integrations/extensions/datadog.mdx
- content/integrations/extensions/new-relic.mdx
Adds an enterprise plan feature callout to the Datadog, New Relic, and data sync extension pages (this already existed for Heap & Segment).
https://docs-git-rt-add-enterprise-only-callouts-extensions-knocklabs.vercel.app/integrations/extensions/datadog
https://docs-git-rt-add-enterprise-only-callouts-extensions-knocklabs.vercel.app/integrations/extensions/new-relic
https://docs-git-rt-add-enterprise-only-callouts-extensions-knocklabs.vercel.app/integrations/extensions/data-sync
> chore: add enterprise feature callout to Datadog, New Relic, and data sync pages

- content/integrations/push/apns.mdx
- content/integrations/push/expo.mdx
- content/integrations/push/firebase.mdx
- content/integrations/push/one-signal.mdx
The PR
- Adds a section on overriding the payload JSON for OneSignal templates
- Cleans up language about payload overrides on the other push provider pages
> chore: document push overrides consistently across providers

- content/preferences/preference-conditions.mdx
Adds a callout warning about using batching with preference conditions, informing users that preference conditions will only be evaluated against the first item in the batch.
[KNO-7317](https://linear.app/knock/issue/KNO-7317/[docs]-add-callout-about-using-preference-conditions-with-batching)
https://docs-git-rt-add-preference-conditions-batching-7c0e0e-knocklabs.vercel.app/preferences/preference-conditions
> chore: add callout about using batching with preference conditions

- content/reference.mdx
Small update to Create schedules endpoint description for grammar.
> fix: grammar on create schedules description

- content/integrations/extensions/overview.md
Add the data warehouse sync extension to the Extensions overview page
> chore: add data warehouse sync to extensions overview

- data/sidebar.ts
Adds the beta tag to message types.
[KNO-7395](https://linear.app/knock/issue/KNO-7395/[doc]-add-a-beta-tag-to-message-type)
> chore: add the beta tag to message types

- content/reference.mdx
This PR updates the `settings` attribute description on the Set tenant endpoint so that it matches the description of that field from the Tenant overview just above. I think this is helpful for surfacing the `logo_url` and
`icon_url` validation information if you're just looking at this endpoint.
> chore: update set tenant endpoint `settings` attribute to match description above

- content/integrations/chat/slack/sending-a-direct-message.mdx
> fix: typo in Slack direct message docs

- content/reference.mdx
Currently, this PR adds missing requirement indicators to clarify whether API attributes/parameters are required or optional for the workflow trigger endpoints _only_. Looking throughout the entire API reference, we inconsistently document this, and I have filed [this Linear ticket](https://linear.app/knock/issue/KNO-7408/[docs]-add-missing-requirements-indicators-to-api-attributesparameters) to capture the larger update that is needed.
> chore: add requirement indicators for workflow trigger endpoints

- content/guides/implementation-guide.mdx
Adds an additional "relevant endpoint" for setting Object preferences to the "Preferences" section of the implementation guide.
> chore: add missing object prefs endpoint to implementation guide

- content/integrations/chat/microsoft-teams/sending-a-message-to-channels.mdx
As per [Microsoft’s docs](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet#:~:text=Posting%20a%20message%20or%20Adaptive%20Card%20to%20a%20private%20channel%20isn%27t%20supported.):
> Posting a message or Adaptive Card to a private channel [as a bot] isn't supported.
[Stack Overflow says the same](https://stackoverflow.com/a/68339371). 🫠
> fix: MS Teams bots cannot message private channels

- content/managing-recipients/setting-channel-data.mdx
Small fix. OneSignal shouldn’t have a space in it.
…there’s nothing wrong with me, really!
> fix: OneSignal is one word

- content/integrations/email/mailgun.mdx
document `o:tag` overrides for mailgun
> feat: support passing multiple tags to mailgun

- content/guides/migrate-from-courier.mdx
Update Courier migration guide in light of some new documentation/product updates they've made. I also added a mention of Partials, plus additional mAPI endpoints for Partials and Layouts.
Note: some info is missing [here](https://www.courier.com/docs/reference/notifications/get-notifications), but I updated to that link because the old link (https://www.courier.com/docs/reference/notifications/list) is broken. It seems like they may be adding templates to their API, at which point I can update the section on migrating workflows/notification templates.
> chore: update courier migration guide

- content/designing-workflows/delay-function.mdx
- content/reference.mdx
Found two lingering uses of "cancelation" and updated per our [style guide](https://www.notion.so/knockapp/Knock-writing-style-guide-9fd5eaf44be54994ad8741d1c86f20f1?pvs=4#62e29a1242e94ea192184f79b24d514e)
https://docs-git-rt-update-spelling-api-docs-knocklabs.vercel.app/reference#payload-size-limit-2
https://docs-git-rt-update-spelling-api-docs-knocklabs.vercel.app/designing-workflows/delay-function#frequently-asked-questions -> "How can I cancel an open delay?"
> chore: update cancelation to cancellation

- content/cli.mdx
Fixes some typos, grammatical errors, and incorrect or missing identifiers on CLI commands
> fix: missing and incorrect info in CLI ref

- content/concepts/commits.mdx
- content/concepts/schedules.mdx
- content/concepts/workflows.mdx
- content/designing-workflows/delay-function.mdx
- content/reference.mdx
- content/send-notifications/triggering-workflows.mdx
This PR:
- [Adds a section to the Workflows concept page about the status setting](https://docs-git-mk-add-workflow-faqs-knocklabs.vercel.app/concepts/workflows#workflow-status)
- [Updates the existing callout on the Commits page to tighten the copy and link back to the new section instead](https://docs-git-mk-add-workflow-faqs-knocklabs.vercel.app/concepts/commits#promoting-commits)
- Adds FAQs about workflow status and expected behavior when set to `Inactive` ([here](https://docs-git-mk-add-workflow-faqs-knocklabs.vercel.app/concepts/workflows#frequently-asked-questions) and [here](https://docs-git-mk-add-workflow-faqs-knocklabs.vercel.app/send-notifications/triggering-workflows#frequently-asked-questions))
- Adds FAQs about expected behavior for …
> chore: document workflow status and versioning more clearly

- data/code/objects/set.ts
Fixes a small error in the Set Object code example for Ruby. We were showing a `data` key rather than the `properties:` keyword argument that is expected (https://github.com/knocklabs/knock-ruby/blob/main/lib/knock/objects.rb#L55-L63)
> fix: Ruby set object example code

- content/concepts/conditions.mdx
This PR adds a section to our Conditions concept page on combining conditions. It moves some content about `AND` and `OR` operators from the section about the conditions editor into the new section, while leaving the screenshots on working with these operators via UI.
It also adds JSON examples for each case, and adds a link back to the mAPI workflow definition for context on the JSON representation.
https://docs-bnt1k892q-knocklabs.vercel.app/concepts/conditions#combining-conditions
> chore: document json representation of combined conditions

- content/integrations/push/apns.mdx
Adds a callout to the APNS integration page regarding the Apple update that will require adding a new cert to server-side Trust Stores prior to February 24, 2025.
I'll make a note to myself to remove this callout after Feb 24.
> chore: add callout re apns trust store certs

- content/reference.mdx
Add [a callout](https://docs-7jrzabsxs-knocklabs.vercel.app/reference#rate-limits) to further clarify that rate limit tiers are _not_ an account or plan setting.
> chore: add callout for rate limit tiers

- content/integrations/push/apns.mdx
- content/integrations/push/expo.mdx
- content/integrations/push/firebase.mdx
- content/integrations/push/one-signal.mdx
- content/integrations/push/token-deregistration.mdx
- content/managing-recipients/setting-channel-data.mdx
Adds token deregistration information to relevant pages across the docs. Also makes some updates to the token deregistration page itself. 
[KNO-7482](https://linear.app/knock/issue/KNO-7482/[docs]-add-calloutslinks-to-token-deregistration-on-setting-channel)
https://docs-git-rt-add-token-deregistration-callout-knocklabs.vercel.app/managing-recipients/setting-channel-data#things-to-know-about-channel-data
https://docs-git-rt-add-token-deregistration-callout-knocklabs.vercel.app/managing-recipients/setting-channel-data#clearing-channel-data
https://docs-git-rt-add-token-deregistration-callout-knocklabs.vercel.app/integrations/push/token-deregistration
https://docs-git-rt-add-token-deregistration-callout-knocklabs.vercel.app/integrations/push/apns#managing-tokens …
> chore: add token deregistration callouts

- content/integrations/chat/slack/overview.mdx
This PR adds information about what Tenant `channel_data` looks like when used to store an `access_token` for a Slack integration (as SlackKit components do OOTB).
It also tweaks the headers in this section of the docs based on the new information, and adds some JSON representations of the schemas that are outlined so that the data shape is crystal clear.
https://docs-ji3im7mte-knocklabs.vercel.app/integrations/chat/slack/overview#how-to-set-channel-data-for-a-slack-integration-in-knock
> chore: add more context on channel data for slack

- content/concepts/recipients.mdx
- content/reference.mdx
Saw there was a little typo (definiton -> definition). Also made a few minor typo updates to the API reference file while I was in there 😄 
[KNO-7529](https://linear.app/knock/issue/KNO-7529/[docs]-fix-typo-for-recipientidentifier-definiton)
> chore: fix definition typo

- content/in-app-ui/react/slack-kit.mdx
This clarifies the technical requirement that the Slack user token must be signed using an RS256 algorithm. While we link to the security and auth docs that state this, this adds the information directly to the Slack docs for token generation.
[KNO-7508](https://linear.app/knock/issue/KNO-7508/[docs]-add-callout-for-using-rs256-algo-in-slackkit-token-generation)
https://docs-git-rt-slack-token-algo-knocklabs.vercel.app/in-app-ui/react/slack-kit#grants-in-the-user-token
> chore: add RS256 requirement to SlackKit docs

- content/reference.mdx
This PR updates the API reference to include the missing values for engagement status filter attributes.
[KNO-7439](https://linear.app/knock/issue/KNO-7439/[switchboard]-update-message-endpoints-to-support-filtering-by)
> fix(KNO-7439): add missing engagement status filters to API reference

- content/preferences/tenant-preferences.mdx
Updates the callout on the tenant preferences page to align with what is under the [tenants page](https://docs.knock.app/concepts/tenants#per-tenant-user-preferences-and-tenant-preference-defaults) to be more explicit about enterprise-only features. 
https://docs-git-rt-update-tenant-preferences-enterpri-8e040f-knocklabs.vercel.app/preferences/tenant-preferences
> chore: update tenant preferences callout

- content/designing-workflows/step-conditions.mdx
Looks like the anchor `#the-trigger-step` was added twice, so it wasn't directing the user to that location on the page.
> chore: update trigger step anchor

- content/getting-started/what-is-knock.mdx
- content/integrations/overview.md
OneSignal was missing from the list of push channels supported on the [What is Knock?](https://docs.knock.app/getting-started/what-is-knock#channels) page, and this PR is to add it in: https://docs-git-rt-add-onesignal-to-channels-knocklabs.vercel.app/getting-started/what-is-knock#channels
> chore: add OneSignal to supported push channels

- content/designing-workflows/template-editor/overview.mdx
This PR [adds an FAQ](https://docs-8z71sj3av-knocklabs.vercel.app/designing-workflows/template-editor/overview#frequently-asked-questions) to the docs on **Why store all of my notification templates in Knock?**
> chore: add guidance on using knock as template source of truth

- content/in-app-ui/react/slack-kit.mdx
In some cases, you might need to include multiple object recipient resource grants on one token, either because they appear on the same page (as requested by someone in Slack) or because you're minting the token at a place in the app that might not know exactly which resource I need to write to, but have permissions to write to more than one.
> chore: add multiple object grant example

- components/Attributes.tsx
Introduces the `isRequired`prop to the `<Attribute>` component, which, when provided, displays a "required" tag.
This PR is _only_ to introduce the prop. I will open a seperate PR with the updates to the API + mAPI docs. 
[KNO-7408](https://linear.app/knock/issue/KNO-7408/[docs]-add-missing-requirements-indicators-to-api-attributesparameters)
Current:
With new `isRequired` prop:
Current:
With new `isRequired` prop:
> feat: introduce isRequired for Attribute component

- content/reference.mdx
This PR updates our API reference for [Slack endpoints](https://docs-6yk682tpc-knocklabs.vercel.app/reference#slack):
- Move body parameters to query parameters
- Remove examples that show required params as a JSON request body
- Document expected response when no `access_token` has been stored in `channel_data` for the given object or tenant
- Update example response for `/channels` endpoint to reflect that it returns a list of `slack_channels`
- Update HTTP method for revoke access endpoint from `GET` -> `PUT`
> fix: slack endpoint documentation (KNO-6503)

- content/concepts/tenants.mdx
- content/send-notifications/triggering-workflows.mdx
This PR removes the "terminology clarification" callout on the [Triggering workflows page](https://docs-git-mk-remove-notify-call-reference-knocklabs.vercel.app/send-notifications/triggering-workflows). I double-checked the full docs site, and the only place that we still referenced a "notify call" was in the title of a code example, which this PR also updates.
While I was here, I also added a backlink to the Preferences overview page from the mention of automatically evaluating user preferences.
What's being removed:
> chore: remove "notify call" callout and add preferences backlink

- content/mapi.mdx
This PR adds a bit more context on how to model `conditions` when working with the mAPI: backlinks to the usage explanation in the documentation, and better examples in the JSON.
> chore: add conditions backlinks and examples to mapi reference (KNO-7163)

- components/PageNav.tsx
This PR includes a few improvements to the "On this page" `<aside>` element that renders a sidebar of the headings on the current page above certain screen widths:
- Increases the width of the sidebar slightly so the instances where we need a horizontal scroll are less likely to occur
- Adds some padding-right to the listed headers so that _when_ horizontal overflow occurs, there is some space on the right side when scrolled all the way to the right
- Slight adjustment to height of the sidebar to make it slightly taller
- Adds a gradient to the bottom of the sidebar so that you can visually tell when there is overflowed content to scroll (in both light and dark mode)
- Wraps the inner content in an additional div so that bottom padding doesn't make the gradient appear above the padding
I …
> chore: "on this page" sidebar improvements (KNO-7487)

- content/send-notifications/tracking.mdx
This PR adds an FAQ section to our docs on link and click tracking, in order to clarify the difference between Knock tracking and provider-specific tracking.
https://docs-git-mk-tracking-clarifications-knocklabs.vercel.app/send-notifications/tracking#frequently-asked-questions
We need to add provider-specific documentation around this topic as well. I was originally going to do that as part of this PR, but as I started to dig in I found that we're pretty inconsistent in how we document even basic things like "Features" (i.e. does a given provider support Knock tracking vs. provider tracking) and "Provider settings" for each provider. I'm going to do a follow-on PR to attempt to address these inconsistencies, in the interest of shipping this FAQ more quickly. 
Example issues:
- Chat/SMS …
> chore (kno-7597): add FAQs to tracking docs

- content/concepts/conditions.mdx
- content/preferences/preference-conditions.mdx
This PR clarifies that preference conditions only support a list of `conditions` that must _all_ evaluate to `true` (i.e. a logical `AND` operation), and that we don't allow `OR` operations or the `any`/`all` syntax from step and channel conditions within the preferences model.
- [Preference conditions](https://docs-git-mk-prefs-conditions-callouts-knocklabs.vercel.app/preferences/preference-conditions)
- [Combining conditions callout](https://docs-git-mk-prefs-conditions-callouts-knocklabs.vercel.app/concepts/conditions#combining-conditions)
> chore: clarify conditions usage for preferences

- content/sdks/react/reference.mdx
As per [my comment](https://github.com/knocklabs/javascript/pull/361#discussion_r1919216141) on knocklabs/javascript#361, `updateConnectedChannels` returns a promise.
[KNO-7658](https://linear.app/knock/issue/KNO-7658/[slackkit]-fix-useconnectedslackchannels-types)
> fix(KNO-7658): fix return type of updateConnectedChannels

- content/reference.mdx
We sometimes return `4xx` status codes that are not explicitly a `400`. This PR updates the explicit `400` mention to be less specific.
> chore: update status code 400 -> 4xx because we return additional codes

- content/reference.mdx
Slack community user pointed out that the `status` options in API reference don't match what's called out on message status docs. I cross-referenced with `MessageStatus` type in Node SDK and updated the API ref: https://github.com/knocklabs/knock-node/blob/f08210b60707f862a21de6b15d1856c3ce47e262/src/resources/messages/interfaces.ts#L64
> chore: update message delivery statuses

- content/integrations/email/layouts.mdx
Updates the Layouts page now that "No layout" is an option on email channel steps. Also fixes wording for some of the buttons etc. that have changed.
https://docs-git-mk-layouts-updates-knocklabs.vercel.app/integrations/email/layouts
Should we call out more-loudly that selecting "No layout" and _not_ including a full HTML document in your email's template could cause errors?
> chore: update layout docs for "no layout" option

- content/integrations/sources/http.mdx
- content/integrations/sources/overview.mdx
- content/integrations/sources/rudderstack.mdx
- content/integrations/sources/segment.mdx
- content/mapi.mdx
- content/send-notifications/testing-workflows.mdx
Uses the "workflow trigger" wording instead of event action mappings and also removes instructions on how to commit them.
[kno-7451](https://linear.app/knock/issue/KNO-7451/docs)
> chore(kno-7451): update docs to use workflow trigger wording instead of event action mappings

- content/integrations/extensions/datadog.mdx
This PR adds the `knock.message_bounced_error.total` metric to our Datadog documentation, and fixes a typo on one of the other metrics. It also removes an attempted hyperlink from one of the metric descriptions, which doesn't work because markdown is not supported within the `Attribute` component.
> chore: update datadog metrics list

- content/guides/alerting.mdx
Expands a section of the docs to address storing per-user alerting options on the object subscription for use in templates and channel data. 
https://docs-git-je-update-alert-guide-knocklabs.vercel.app/guides/alerting#subscribe-users-to-the-alert
> chore: add per-user property example to alerting guide

- content/integrations/push/apns.mdx
This PR removes the callout on our APNS docs regarding the Apple cert update requirement, now that the deadline for that update has passed.
> chore: remove APNS cert update callout

- content/integrations/email/sendgrid.mdx
Adds callouts explaining that Knock currently only handles synchronous bounces for SendGrid through delivery status checks and that asynchronous bounces (which may occur after a message is marked as delivered) are not currently reflected in Knock's delivery status.
https://docs-git-rt-clarify-sendgrid-bounce-support-knocklabs.vercel.app/integrations/email/sendgrid
> chore: clarify SendGrid async bounce handling limitations

- content/integrations/sources/hightouch.mdx
This PR updates the rate limit on our Hightouch guide for the user identification endpoint. This [endpoint](https://docs.knock.app/reference#identify-user) is categorized as `Tier 3`, which supports 60 requests per second.
> fix: correct rate limit for user identify endpoint

- content/reference.mdx
Clarify "nested data structure" for `combined_trigger_data` in our docs.
> chore: clarify supported values for truncated trigger data

- content/integrations/sms/messagebird.mdx
This PR updates the external link on our MessageBird integration page to point to MessageBird's documentation, because the current link (confusingly) redirects to the Bird homepage. It also adds a callout about Bird's rebrand, and that our current integration is with the legacy MessageBird API (which is no longer accepting new customers).
Finally, it also includes a link to get in touch if access to a Bird integration is a blocker.
https://docs-k6nkbx2pp-knocklabs.vercel.app/integrations/sms/messagebird
> chore: MessageBird update

- content/integrations/extensions/data-sync.mdx
Adds `actors` to the messages table on the data export page.
> chore(pla-966): dw messages actor export docs

- content/send-notifications/triggering-workflows/overview.mdx
Small fix to update hyperlink syntax in a callout block
> fix: markdown -> a tag hyperlink syntax in callout component

- content/reference.mdx
Following up on our pairing session, updating the description for the GET user channel data and GET object channel data descriptions to be more specific to each endpoint.
> chore: fix descriptions for GET channel data endpoints to be specific to each endpoint

- content/integrations/email/attachments.mdx
Adds information about our support of `Content-ID` with inline email attachments for certain providers.
> chore: add content-id info for email attachments

- content/concepts/objects.mdx
This PR removes "coming soon" and "near-term" language from our messaging about Object support on the in-app feed.
**Before**
**After**
> chore: remove near-term language from object feed mentions

- content/concepts/subscriptions.mdx
- content/send-notifications/canceling-workflows.mdx
Add FAQs to call out that it is possible to cancel fanned-out workflow recipient runs, even if a given recipient was not explicitly included in the workflow trigger's `recipients`.
> chore: add context on subscriber fanout cancellations

- content/sdks/android/deep-links.mdx
This PR updates the example payload override (and backlink to more info on overrides) in our Android SDK documentation. FCM requires a specific payload override structure (everything needs to be nested under a `data` key), and the current example caused confusion for a customer. The link now points to FCM-specific docs.
I also opted for a copyable JSON example as opposed to a screenshot from the dashboard, but can update it to be in an image again if people like that better. Original is [here](https://docs.knock.app/sdks/android/deep-links#2-include-a-deep-link-in-your-knock-message-payload) for reference.
> fix: override example for fcm with android sdk

- data/code/users/bulk-identify.ts
- data/code/users/identify.ts
Shows these properties as optional.
> fix(kno-8189): user properties should be optional in the go sdk

- content/reference.mdx
Updates [the get feed endpoint](https://docs-git-rt-add-date-range-filters-feed-knocklabs.vercel.app/reference#query-parameters-6) to add the newly supported inserted_at filters.
> feat: add inserted_at filters for feed

- content/in-app-ui/message-types.mdx
This PR updates the in-app message types doc to include the following message types:
- `"button"`
- `"url"`
- `"image"`
[KNO-8215](https://linear.app/knock/issue/KNO-8215/[docs]-update-message-types-doc)
> feat(KNO-8215): add button, url, and image fields to message types doc

- .env
- pages/api/search.ts
Exposes a new `POST /api/search` endpoint that proxies through to inkeep to expose search results over their RAG completions API.
We'll expose this as a `search_documentation` tool in the MCP server/agent tooklit
KNO-8245
> feat: expose new rag search endpoint

- content/sdks/android/deep-links.mdx
- content/sdks/ios/deep-links.mdx
This PR fixes erroneous information on the Android deep linking guide (removes mentions of XCode and adds information about Android Studio and intent filters). It also:
- Updates usage to comply with style guide for both Android and iOS
- Adds Step and Accordion components for better organization 
- Adds a brief mention w/ link to more info about verifying app links on Android to correlate with "universal links" on iOS.
[iOS](https://docs-c15b9wa03-knocklabs.vercel.app/sdks/ios/deep-links)
[Android](https://docs-c15b9wa03-knocklabs.vercel.app/sdks/android/deep-links)
We should also make similar improvements to the "Push notifications" pages under each of these sections.
> chore(kno-8186): improve mobile deep linking docs

- components/ApiReference/SchemaProperties/SchemaProperties.tsx
- components/ApiReference/SchemaProperties/SchemaProperty.tsx
- components/ApiReference/SchemaProperties/helpers.ts
Minor API spec fixes:
- Filter `null` type
- Show count of possible types
> chore: fix union type display

- content/integrations/chat/microsoft-teams/overview.mdx
It’s not clear from our docs what the JSON payload should look like when a user wants to send a custom Adaptive Card to Microsoft Teams, so this PR adds an example.
[KNO-8385](https://linear.app/knock/issue/KNO-8385/update-ms-teams-docs-to-better-describe-using-custom-adaptive-cards)
> feat(KNO-8385): add example JSON for MS Teams Adaptive Cards

- data/sidebar.ts
Remove outdated Message types components link from React UI sidebar.
> chore: remove sidebar link for react message types

- content/in-app-ui/message-types.mdx
The `multi_select` field was missing from our in-app message types docs. 🤷🏻‍♂️
> fix: add multi_select field to message types doc

- content/concepts/audiences.mdx
- content/concepts/broadcasts.mdx
- data/sidebar.ts
Remove beta tags from audiences, broadcasts, and 1-click. Will deploy Wed.
https://linear.app/knock/issue/KNO-8534/remove-beta-flag-from-audiences-and-broadcasts
> chore: remove beta tags from audiences, broadcasts, and 1-click

- components/ui/ApiReference/ApiReferenceMethod/ApiReferenceMethod.tsx
- components/ui/ApiReference/helpers.ts
- data/specs/api/openapi.yml
- data/specs/api/stainless.yml
Message status responses weren't showing because they reference "allOf" the Message schema in the OpenApi spec. 
[KNO-8549: \[docs\] fix mark messages status schemas](https://linear.app/knock/issue/KNO-8549/[docs]-fix-mark-messages-status-schemas)
> fix(kno-8549): fix message status schemas

- content/tutorials/implementation-guide.mdx
- content/tutorials/migrate-from-courier.mdx
This PR updates the placeholder syntax in the listed endpoints in our integration/migration guides to reflect the new syntax:
`https://api.knock.app/v1/objects/:collection/:id/subscriptions` -> `https://api.knock.app/v1/objects/{collection}/{object_id}/subscriptions`
It also adds the new bulk schedules endpoint and clarifies the language around creating schedules for multiple recipients at a time.
> chore: update endpoints in tutorials with new placeholder syntax

- components/ui/Breadcrumbs.tsx
Small "fix". We'll have to revisit how we handle rendering the links here
> fix: stop rendering broken breadcrumbs

- next.config.js
Fixing an issue where going directly to an SDK URL would 404
> fix: redirecting directly to SDK

- data/sidebars/inAppSidebar.ts
- next.config.js
- scripts/generateLlmsTxt.ts
I had a file locally that was not being generated -- added better error handling so we can more easily detect when a page isn't being generated. That also helped pick up that .md files weren't being picked up either
> fix: 404s for markdown and in-app feeds

- content/integrations/extensions/data-sync.mdx
Made some updates to the Prequel docs to remove some unhelpful links and better clarify the process.
I feel like this whole page is a bit redundant, when you look at what we list at the top, under "How it works," and then again under "Setup." What I've done here is mostly just to make things a bit clearer and more accurate, but I would also be in favor of just condensing the information under a single "How it works" or "Setup" section if other folks think that would be better
https://docs-git-mk-update-prequel-docs-knocklabs.vercel.app/integrations/extensions/data-sync
> chore: update prequel setup docs

- components/ui/ApiReference/ApiReference.tsx
- components/ui/Page/helpers.ts
- styles/index.css
**Problem:**
When the page is scrolled down from the top, typing into the global search input located in the PageHeader causes the page viewport to incrementally scroll upwards with each keystroke. This behavior was observed across multiple browsers (Chrome, Safari).
**Root Cause:**
The root cause was identified as the global CSS rule `scroll-padding-top: var(--top-padding);` applied to the html element in styles/index.css. This property, intended to add padding above targets of fragment identifier navigation (# links) to prevent them from being obscured by sticky headers, was being incorrectly applied by browsers during input focus events. When typing into the search input while the page was scrolled, the browser attempted to ensure the focused input respected this top padding, resulting …
> fix(kno-8569): stop scrolling when typing in search bar

- content/in-app-ui/message-types.mdx
Found a broken `<Callout>` so I fixed it. 😎   
[KNO-8617](https://linear.app/knock/issue/KNO-8617/docs-fix-callout-in-message-types-doc)
> fix(KNO-8617): fix feeds v. guides callout in message types doc

- content/concepts/guides.mdx
The content of [/concepts/guides](https://docs.knock.app/concepts/guides) and [/in-app-ui/guides/overview](https://docs.knock.app/in-app-ui/guides/overview) was duplicative. To dedupe, the content of /concepts/guides has been updated to include Thomas's walkthrough video and new copy explaining guides at a high-level.
> feat: update /concepts/guides to dedupe content

- components/ui/Page/Sidebar.tsx
To trigger currently, expand the sidebar menus until it can scroll. Then changing pages will cause a small jump in the scroll of the main content. Not sure why exactly. But this fixes it!
Originally changed to sticky in anticipation of a footer but we'll come back to that if we do
> fix: scroll jumps on navigation

- content/designing-workflows/partials.mdx
This PR attempts to clarify some of the current limitations of Partials and how Liquid variables can be used within a partial's content. It adds some FAQs to address a few common questions/patterns we've seen from customers.
- https://docs-git-mk-partials-clarifications-knocklabs.vercel.app/designing-workflows/partials#using-partials-in-templates
- https://docs-git-mk-partials-clarifications-knocklabs.vercel.app/designing-workflows/partials#frequently-asked-questions
> chore: add partials FAQs and clarifications on variable inputs

- components/ui/Autocomplete.tsx
> fix: search container height too big on few results

- content/managing-recipients/identifying-recipients.mdx
A simple warning callout on the existing recipient identification docs page.
> feat(pla-1336): document new custom properties size limit for recipients

- components/ui/CollapsibleNavItem.tsx
- components/ui/Feedback.tsx
- components/ui/Page/Sidebar.tsx
- content/in-app-ui/guides/overview.mdx
- data/sidebars/inAppSidebar.ts
Guides needs a beta indicator. Instead of putting it on the Overview page, let's enable CollapsibleNavItems to accept an `isBeta` prop and render it at the top level
> feat: collapsible menus can have beta tag

- content/send-notifications/triggering-workflows/api.mdx
Documents limits on `data` payload size, for the full payload and individual string values.
> chore: add trigger data size limits

- components/ui/NavItem.tsx
- components/ui/Page/Sidebar.tsx
- components/ui/Page/helpers.ts
- data/sidebars/developerToolsSidebar.ts
- data/sidebars/integrationsSidebar.ts
- data/sidebars/tutorialsSidebar.ts
- data/types.ts
- hooks/useSidebarContent.ts
- layouts/DocsLayout.tsx
- layouts/IntegrationsLayout.tsx
- lib/content.ts
- scripts/generateLlmsTxt.ts
- styles/global.css
This PR allows us to have non-nested sidebar items, so that we don't need to wrap "Developer tools" under a developer tools section in the sidebar. It does this by introducing a new recursive `SidebarContent` type, which can then have subpages (or subpages of subpages).
Most of the changes here are reworking the breadcrumbs as those were most borked because of this. It could definitely do with another pass later, but I think this should suffice for now. 
I implemented the changes in the following places:
- Integrations > Overview
- Developer tools
- Tutorials
> feat: allow sidebar to not be nested

- content/in-app-ui/message-types.mdx
This PR clarifies that template previews for message types are not part of the message generated by a guide.
https://docs-git-mk-kno-8725-knocklabs.vercel.app/in-app-ui/message-types#template-previews
> chore: clarify message type template previews

- data/sidebars/mapiOverviewSidebar.ts
- data/specs/mapi/customizations.yml
We had missed adding this to the sidebar, so this content wasn't getting rendered.
[https://linear.app/knock/issue/KNO-8785/docs-api-keysexchange-endpoint-not-present-in-mapi-docs](https://linear.app/knock/issue/KNO-8785/docs-api-keysexchange-endpoint-not-present-in-mapi-docs)
---
In search too:
> fix: adds API Keys section to mAPI

- content/concepts/guides.mdx
Small description of guides analytics that we can link to from the dashboard.
> feat: add guides analytics info

- components/ui/Autocomplete.tsx
- components/ui/Page/Sidebar.tsx
- components/ui/Page/helpers.ts
- content/__api-reference/content.mdx
- content/__mapi-reference/content.mdx
[[Docs] Bug in redirect from search to API Reference](https://linear.app/knock/issue/KNO-8744/docs-bug-in-redirect-from-search-to-api-reference)
This PR makes navigating to API reference pages more consistent.
The problem was that we'd try to navigate to the section prematurely, as the page was still rendering (API references are big pages, so this takes time). I added a check to make sure the page was at its final height before navigating.
Also, the sidebar wouldn't open in Scoti's video because SlackChannelData is a deeply nested page. Sidebar open state code didn't account for pages that were nested this deeply, so I made the function recursive to handle infinitely nested pages.
> fix(kno-8744): more consistent API linking

- content/integrations/email/settings.mdx
Settings like from, to, reply to, etc. will be moved from the template settings modal to the editor itself, so this reflects that change.
> fix: change template level settings from modal to editor

- content/cli.mdx
- content/developer-tools/integrating-into-cicd.mdx
- content/developer-tools/knock-cli.mdx
- data/sidebars/cliSidebar.ts
- pages/cli/[...slug].tsx
This PR:
- Updates the Knock CLI reference to describe the new `knock push` and `knock pull` commands.
- Updates the CI/CD guide to reference these new commands and fix broken links.
There’s a small bug that affects the CLI reference sidebar. Notice in the video below, as I scroll to the sections for `knock push` and `knock pull`, the sidebar doesn’t correctly highlight the corresponding entries. I plan to address this in a follow-up, so that this PR focuses on the docs content itself.
https://github.com/user-attachments/assets/c4c20353-856c-4c7c-8a88-868ad2dc9b76
[KNO-8819](https://linear.app/knock/issue/KNO-8819/docs-describe-new-knock-push-and-knock-pull-commands)
> feat(KNO-8819): add push and pull commands to CLI reference

- components/ui/PreTextDiagram.tsx
- content/cli.mdx
- content/concepts/translations.mdx
- content/concepts/workflows.mdx
- content/integrations/email/layouts.mdx
- lib/mdxComponents.tsx
This PR adds a new component `<PreTextDiagram>` to render diagrams made of pre-formatted text, including file tree diagrams.
[KNO-8866](https://linear.app/knock/issue/KNO-8866/docs-add-pre-formatted-text-diagram-component)
> chore(KNO-8866): add PreTextDiagram component

- package.json
- yarn.lock
[`@analytics/segment`](https://github.com/DavidWells/analytics/tree/master/packages/analytics-plugin-segment) was added by #500, but I’m pretty sure this dependency is entirely unused. That same PR also installed and set up [`@segment/snippet`](https://github.com/segmentio/snippet).
This PR removes `@analytics/segment` from the dependencies, to resolve [this automated Dependabot alert](https://github.com/knocklabs/docs/security/dependabot/30).
[KNO-8906](https://linear.app/knock/issue/KNO-8906/docs-remove-analyticssegment-dependency)
> chore(KNO-8906): remove @analytics/segment dependency

- content/concepts/schedules.mdx
- content/developer-tools/migration-guides/go.mdx
- content/developer-tools/migration-guides/java.mdx
- content/developer-tools/migration-guides/node.mdx
- content/developer-tools/migration-guides/python.mdx
- content/developer-tools/migration-guides/ruby.mdx
Made updates to the following pages to improve consistency, align pages with Knock's style guide, and correct errors in code examples.
- [/concepts/schedules](https://docs-git-sd-kno-8865-sdk-migration-guides-knocklabs.vercel.app/)
- [/developer-tools/migration-guides/node](https://docs-git-sd-kno-8865-sdk-migration-guides-knocklabs.vercel.app/developer-tools/migration-guides/node)
- [/developer-tools/migration-guides/python](https://docs-git-sd-kno-8865-sdk-migration-guides-knocklabs.vercel.app/developer-tools/migration-guides/python)
- [/developer-tools/migration-guides/java](https://docs-git-sd-kno-8865-sdk-migration-guides-knocklabs.vercel.app/developer-tools/migration-guides/java)
- [/developer-tools/migration-guides/ruby](https://docs-git-sd-kno-8865-sdk-migration-guides-knocklabs.ve …
> chore: improvements to new SDK migration docs

- package.json
- yarn.lock
Prism v1.29.0 has a security vulnerability. (See [the Dependabot alert for CVE-2024-53382](https://github.com/knocklabs/docs/security/dependabot/25).)
Prism is required by both [React Syntax Highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) and [refractor](https://github.com/wooorm/refractor), a transitive dependency of React Syntax Highlighter.
The author of refractor has indicated [he does not intend to cut a v3.6.1 release of refractor to update Prism](https://github.com/wooorm/refractor/issues/75#issuecomment-2815231981). In addition, there’s been no movement on upgrading refractor in the React Syntax Highlighter codebase. (See react-syntax-highlighter/react-syntax-highlighter#591 and react-syntax-highlighter/react-syntax-highlighter#592.)
So, to …
> chore(KNO-8908): add version override for prismjs 

- package.json
- yarn.lock
[Commitizen](https://commitizen.github.io/cz-cli/) is installed in this repo, but it seems we never actually finished setting it up.
This PR removes Commitizen and an associated adapter, `cz-conventional-changelog`, so that we can resolve [the Dependabot alert for CVE-2024-4067](https://github.com/knocklabs/docs/security/dependabot/6).
[KNO-8909](https://linear.app/knock/issue/KNO-8909/docs-remove-commitizen)
> chore(KNO-8909): remove Commitizen

- content/getting-started/what-is-knock.mdx
This PR updates the "What is Knock?" documentation page to provide a more comprehensive overview of Knock's capabilities.
**Why:**
The primary goal is to reflect that Knock powers a broader range of messaging needs beyond just workflows, specifically including:
- **Workflows:** Transactional and lifecycle messaging.
- **Broadcasts:** One-time announcements and campaigns.
- **Guides:** In-app lifecycle messaging.
The terminology has also been updated to consistently use "messaging" instead of "notifications" to better reflect this broader scope and position Knock as a complete messaging platform.
**How:**
- The introductory paragraph has been rewritten to clearly state Knock's role as "product and customer messaging infrastructure" and list the core messaging types.
- New dedicated …
> Update "what is knock" page content

- content/integrations/email/attachments.mdx
This PR documents the update made in KNO-6590 to make `attachments` the default key for email attachments
> chore(kno-6590): add new default attachments key behavior

- components/ui/Autocomplete.tsx
- styles/index.css
We weren't using `LeadingComponent` and `TrailingComponent` for those UI elements with search, which lead to UI jank. This PR updates the Autocomplete component to implement `@telegraph/input` correctly.
> fix: implement telegraph input properly with search

- content/send-notifications/tracking.mdx
This PR adds a callout to our link click tracking documentation to make it more-obvious that the https:// protocol is required for link tracking to work.
> chore(kno-8887): call out https protocol requirement

- content/integrations/chat/microsoft-teams/overview.mdx
Updates the Microsoft Teams overview page to correctly reference the Integrations tab in our dashboard for setting up a new Teams channel in Knock.
H/T @jonathanberger
> chore: update Teams instructions for adding channel

- content/send-notifications/triggering-workflows/api.mdx
This PR updates the description for trigger data to clarify limits on string size for log truncation.
> chore(kno-9043): clarify trigger data limits

- content/developer-tools/outbound-webhooks/overview.mdx
This PR updates the code example on verifying webhook signatures with the following:
- Added missing `require("crypto")`
- Stringify the `request` body
- Use `Buffer.from` for `timingSafeEqual()`
- Fixed timestamp check:
- Now actually uses a 5-minute window (300000 ms).
- Uses Date.now() correctly and compares absolute difference.
> chore(kno-9169): update webhook sig verification example

- content/integrations/extensions/data-sync.mdx
This PR cleans up the language for the setup process in the data warehouse sync documentation based on some customer confusion and feedback that we've gotten.
> chore: clean up setup instructions for data warehouse sync

- content/concepts/audiences.mdx
- content/concepts/broadcasts.mdx
Our audiences and broadcast pages currently lack tags, this PR should help people find what they're looking for in docs search when they want to learn more about targeting messages to specific user cohorts and one-time sends.
> chore: add tags for audiences and broadcasts

- content/developer-tools/mcp-server.mdx
This PR updates the manual MCP server install instructions to reflect updates that Cursor made to their settings:
> chore: update cursor install instructions

- content/tutorials/migrate-from-braze.mdx
- data/sidebars/tutorialsSidebar.ts
This PR introduces a new tutorial for customers to use when migrating from Braze to Knock. This tutorial focuses solely on transactional messaging, so broadcasts/guides are not included in this initial version. 
https://docs-git-rt-migrate-from-braze-knocklabs.vercel.app/tutorials/migrate-from-braze
> chore: add Braze migration tutorial

- content/in-app-ui/react/sdk/reference.mdx
- content/in-app-ui/react/teams-kit.mdx
- content/integrations/chat/microsoft-teams/overview.mdx
- content/integrations/chat/microsoft-teams/sending-a-direct-message.mdx
- content/integrations/chat/microsoft-teams/sending-a-message-to-channels.mdx
This PR updates the Microsoft Teams docs to replace references to bot credentials with Graph API-enabled application credentials wherever applicable. After knocklabs/control#5573 is released, TeamsKit will use two new channel settings, “Graph API client ID” and “Graph API client secret”, instead of the MS Teams bot’s own credentials.
[KNO-9264](https://linear.app/knock/issue/KNO-9264/docs-update-teamskit-docs-to-describe-new-graph-api-app-credentials)
> chore(KNO-9264): reference Graph API client credentials in MS Teams docs

- content/integrations/push/expo.mdx
This PR updates the Expo "silent" push documentation to reflect the changes made in KNO-9285 to send the correct key (`_contentAvailable`) for silent push.
> chore: fix key for expo silent push

- content/integrations/sources/segment.mdx
This PR attempts to clarify expected mapping of traits from a Segment `Identify` event to a user in Knock.
> chore: clarify segment identify event mapping

- content/integrations/extensions/data-sync.mdx
This PR adds a table of Prequel-supported warehouse destination types to our docs so that our customers don't need to click through to Prequel documentation. For now, this list does not include types that are in beta status.
https://docs-git-mk-kno-9345-knocklabs.vercel.app/integrations/extensions/data-sync
Original list for comparison: https://docs.prequel.co/docs/destinations-overview#supported-destinations 
1. Right now these are in the same order as Prequel lists them (loosely organized by "type" of destination). Would it be better to simply list them alphabetically?
2. Do we want to include destinations that are marked as "beta" on Prequel? These are theoretically available, but mileage may vary pending any unforeseen issues Prequel-side.
> chore: add supported destinations to warehouse sync docs

- content/integrations/email/postmark.mdx
This PR adds guidance on how to support Postmark's `MessageStream` feature for broadcast emails via payload overrides in Knock.
http://docs-git-mk-kno-8334-knocklabs.vercel.app/integrations/email/postmark
> chore(kno-8334): add message stream guidance for Postmark

- content/integrations/email/settings.mdx
Adds additional guidance to the documentation about `to` overrides for emails to call out caveats of providing multiple email addresses. 
https://docs-nho25s3nr-knocklabs.vercel.app/integrations/email/settings
> chore: add multi-email `to` override guidance

- content/concepts/broadcasts.mdx
This PR adds a callout to the Broadcast concept page to make clear that all data upserted via CSV will be strings.
> chore(kno-9469): add callout on CSV data upsert type

- content/in-app-ui/android/sdk/overview.mdx
- content/in-app-ui/expo/sdk/overview.mdx
- content/in-app-ui/flutter/sdk/overview.mdx
- content/in-app-ui/ios/sdk/overview.mdx
- content/in-app-ui/javascript/sdk/overview.mdx
- content/in-app-ui/react-native/sdk/overview.mdx
- content/in-app-ui/react/sdk/overview.mdx
- content/manage-your-account/data-retention.mdx
This PR removes outdated references to a "Help" dropdown to contact support from throughout the docs.
> fix(kno-9514): remove outdated help references

- content/concepts/workflows.mdx
This PR clarifies the expected behavior around workflow cancellation if a given workflow's status is changed to `Inactive`.
https://docs-git-mk-kno-8920-knocklabs.vercel.app/concepts/workflows#workflow-status
https://docs-git-mk-kno-8920-knocklabs.vercel.app/concepts/workflows#frequently-asked-questions
> chore(kno-8920): clarify inactive status terminations

- content/cli.mdx
Add docs for new CLI filtering on commits (PR: https://github.com/knocklabs/knock-cli/pull/576)
KNO-9201
> chore: add docs for resource filtering in CLI

- data/code/api/idempotency.ts
This PR updates the idempotency code example for our Node.js SDK to pass in the `idempotencyKey` option, reverting the change to the Node.js example made by #1125.
[`@knocklabs/node` v1.17.0](https://github.com/knocklabs/knock-node/releases/tag/v1.17.0) made it so that specifying the `idempotencyKey` option will automatically set the `Idempotency-Key` request header, whereas this was not the case with prior releases.
Our Go SDK doesn’t actually have a `WithIdempotencyKey` function, so I’ve kept the Go example using `WithHeader`.
[KNO-9099](https://linear.app/knock/issue/KNO-9099/node-sdk-improve-idempotency-key-handling)
> chore(KNO-9099): update idempotency code example for Node.js SDK

- data/code/api/idempotency.ts
[v1.18.0 of our Go SDK](https://github.com/knocklabs/knock-go/releases/tag/v1.18.0) includes a `WithIdempotencyKey` function. This PR updates the idempotency code example for the Go SDK to make use of `WithIdempotencyKey`.
[KNO-9901](https://linear.app/knock/issue/KNO-9901/docs-add-withidempotencykey-to-go-sdk-idempotency-example)
> chore(KNO-9901): update idempotency code example for Go SDK

- data/sidebars/apiOverviewSidebar.ts
- data/sidebars/mapiOverviewSidebar.ts
- data/specs/api/customizations.yml
- data/specs/api/stainless.yml
- data/specs/mapi/customizations.yml
Previously, there were two issues:
- no shared resource section on mapi
- shared resource section on api used wrong key in stainless spec `shared` instead of the correct [Stainless-specific](https://www.stainless.com/docs/guides/configure#shared-models) `$shared`
Step one of this fix was making sure we use the $shared key in Stainless config. This will update our SDKs so `shared` is not an accessible resource.
This PR adds the new stainless config ^ so API reference is updated and _adds_ the shared section to mAPI
Example:
This URL doesnt work on live docs: https://docs.knock.app/mapi-reference/$shared/schemas/page_info
and now it works!
https://linear.app/knock/issue/KNO-8851/docs-404s-on-shared-schemas-within-mapi
> fix(kno-8851): include shared resources in API references
