content/concepts/objects.mdx, content/managing-recipients/setting-preferences.mdx, content/reference.mdx
Fixes some discrepancies in the docs
KNO-4667
=> fix: correct bulk docs

content/concepts/preferences.mdx, content/reference.mdx
- Adds tenant overlay support for getting preferences
- Adds an example of preference conditions into the concepts guide
[KNO-4757](https://linear.app/knock/issue/KNO-4757)
=> feat: add support for tenant overlays in preferences

content/reference.mdx
Add reference to actors under messages.
KNO-4756
=> feat: add reference to actors under messages

content/concepts/variables.mdx
Update the instructions on how to set an environment-specific variable to provide better clarity for users.
=> fix: update instructions for setting environment-specific variables

content/in-app-ui/security-and-authentication.mdx
Update docs so they're compatible with the latest Node SDK changes
=> chore: update signUserToken example usage

content/in-app-ui/react/custom-notifications-ui.mdx, content/in-app-ui/react/inbox.mdx, content/in-app-ui/react/migrating-from-react-notification-feed.mdx, content/in-app-ui/react/overview.mdx, content/in-app-ui/react/reference.mdx, content/in-app-ui/react/toasts.mdx, data/sidebar.ts
- Updates docs to reference `@knocklabs/react`
- Add migration guide
- Update reference
[KNO-4945](connor-kno-4945-docs-for-knocklabsreact-and-migration-guide)
=> feat: update docs to reference new react package and providers

content/in-app-ui/android/overview.mdx, content/in-app-ui/android/quick-start.mdx
Updating Android documentation based on new installation method
=> feat: Update android docs

content/designing-workflows/batch-function.mdx
This PR makes a small update to its reference to the dashboard UI, to accompany [this PR](https://github.com/knocklabs/control/pull/2838)
=> chore: update docs to reflect UI update for sliding batches

content/in-app-ui/javascript/reference.mdx, content/in-app-ui/react/reference.mdx, content/in-app-ui/security-and-authentication.mdx
- Add new docs for `onUserTokenExpiring`
- Add new section to in-app UI security on token refreshing
=> chore: add token expiring callback docs

content/in-app-ui/react/slack-kit.mdx
=> fix(kno-5354): typo - remove extra *

content/in-app-ui/react/reference.mdx
Fixes layout + adds missing type
[KNO-5355](https://linear.app/knock/issue/KNO-5355/fix-react-api-reference-layout)
=> fix(kno-5355): fix reference layout

content/in-app-ui/react/reference.mdx, content/in-app-ui/react/slack-kit.mdx
Add the connected channel tag attr to the combobox and slack kit documentation.
KNO-5368
=> chore(kno-5368): add connected channel tag attr

app/robots.ts, app/sitemap.ts, lib/constants.ts, netlify.toml, next-env.d.ts, public/robots.txt, tsconfig.json
- Adds a dynamic `sitemap.xml` and `robots.txt`
[KNO-5429](https://linear.app/knock/issue/KNO-5429)
=> chore: add dynamic sitemap and robots

content/designing-workflows/template-editor/overview.mdx
=> fix: typo on template editor overview page

content/integrations/chat/whatsapp.mdx
=> fix: typo in whatsapp docs

content/concepts/users.mdx
Adds links to the Users concepts page on how to update or edit a user's information.
=> Chore: Add update user info

content/in-app-ui/react/slack-kit.mdx, content/integrations/chat/slack-kit/overview.mdx
Catch a few of Meryl's copy edits I missed on the original PR
=> fix: small copy edits

components/Accordion.tsx, components/Card.tsx, components/Step.tsx, content/playground.mdx, pages/[...slug].tsx
- Add new `AccordionGroup` and `Accordion`
- Add new `Steps` and `Step`
- Add new `/playground` page
=> chore: add new accordion and step components

content/getting-started/quick-start.mdx
This PR updates the Quick start guide to use the new `Step` and `Accordion` components.
=> chore: update quick start with new components

hooks/useInKeepSettings.ts
This PR updates the Default View for Inkeep so that the "Ask AI" link in our main search opens up the same "AI Chat" view as the button in the lower right corner.
https://www.loom.com/share/f7edff5c7c17492c985be15aa4abce55?sid=b8a91d06-6fcc-46a8-bb66-bdb5df4da95d
=> chore: update Inkeep default view

content/managing-recipients/setting-preferences.mdx
=> fix: typo on setting preferences

content/reference.mdx
Add new option for passing `?include[]=preferences` to the user and objects API endpoints
KNO-5648
=> feat: add include preferences option for users and objects

components/Step.tsx
Possible optimization to the `<Step>` component to enable linking from the "On this page" nav for `h2` and `h3` headers.
Example: https://docs-p11j72z7f-knocklabs.vercel.app/getting-started/quick-start
=> chore: add anchor links to step components

content/integrations/push/firebase.mdx
Add additional detail about how payload overrides work with FCM.
=> chore: clarify payload overrides for FCM

components/Callout.tsx, content/concepts/commits.mdx
=> chore: add docs for commit revert

content/concepts/preferences.mdx
quick reorder of headings based on recent questions about environment defaults
=> chore:reorder pref headings

content/designing-workflows/send-windows.mdx
This PR attempts to clarify the queued message behavior of send windows
=> chore: clarify queue behavior on send windows

content/integrations/sources/segment.mdx
I updated the Segment source page to use the new step and accordion components, made a few other formatting changes, and added an FAQ section.
Would love feedback on the two FAQ items. Specifically, I debated the following when thinking about adding this and where:
- The process is essentially the same, so should we combine them and adjust the language?
- Does it make sense to have them as FAQs, or should we instead add them as a section (possibly after "Committing the event action configuration")?
Preview: https://docs-git-rt-update-segment-source-events-knocklabs.vercel.app/integrations/sources/segment
=> chore: update segment source doc page

content/playground.mdx
Add note on use of `Card` component on Playground page to call out ability to open link in new tab.
=> chore: add instructions for use of `Card` component to playground

pages/[...slug].tsx, pages/_app.tsx, pages/index.tsx
=> fix: anchor link nav cutting off top nav

content/designing-workflows/batch-function.mdx, content/designing-workflows/delay-function.mdx, content/designing-workflows/throttle-function.mdx
- Adds new docs for window rules on throttles, delays, and batch steps
- Restructures existing window content into an accordion and adds examples
KNO-5883
=> feat: add docs for window rules on batch, delay, throttle

components/MultiLangCodeBlock.tsx, content/integrations/push/one-signal.mdx, content/integrations/push/overview.mdx, data/code/users/set-channel-data-one-signal.ts, data/integrationsSidebar.ts
Adds documentation for OneSignal push integration
[KNO-5890](https://linear.app/knock/issue/KNO-5890/%5Bonesignal%5D-docs)
=> feat: add one signal push integration docs

content/in-app-ui/overview.mdx, content/in-app-ui/react/feed.mdx, content/in-app-ui/react/toasts.mdx, content/integrations/in-app/overview.mdx, content/sdks/react/overview.mdx
Updates the URL for the live demo to use the custom domain.
=> fix: update live demo URL

content/integrations/sms/twilio.mdx
=> fix: small typo

content/sdks/javascript/reference.mdx
Adds documentation for the user client methods that are available in the JS SDK
[KNO-5960](https://linear.app/knock/issue/KNO-5960/docs-for-user-client)
=> Add user client method documentation

content/sdks/react-native/overview.mdx, content/sdks/react-native/push-notifications.mdx, content/sdks/react-native/quick-start.mdx, content/sdks/react-native/reference.mdx, data/sidebar.ts
Updating the React Native docs to include information on the KnockExpoPushNotificationProvider as well as adding a QuickStart and PushNotification guide.
=> React Native Doc Updates

content/integrations/email/aws-ses.mdx
This PR removes some redundancies in the AWS SES setup guide and also adds step and accordion components to improve readability
https://docs-2z75lhhm0-knocklabs.vercel.app/integrations/email/aws-ses
=> chore: update AWS SES instructions

content/integrations/email/resend.mdx
Add delivery tracking to Resend feature list
linked to https://github.com/knocklabs/switchboard/pull/2394
=> feat(kno-5848): add delivery tracking to resend

content/in-app-ui/react-native/notification-feeds.mdx, content/in-app-ui/react/custom-notifications-ui.mdx, content/sdks/react-native/notification-feeds.mdx, content/sdks/react-native/quick-start.mdx, content/sdks/react-native/reference.mdx, content/sdks/react/reference.mdx, yarn.lock
* Adds new docs for new `useNotificationStore` hook
* Removes all `zustand` usage
=> chore: add usenotifstore docs and remove zustand usage

content/designing-workflows/channel-step.mdx
=> fix: update link

content/concepts/translations.mdx
=> fix: update broken translation links

content/managing-recipients/overview.mdx
=> fix: update setting channel data link

content/in-app-ui/angular/overview.mdx
=> fix: add mailto link

content/managing-recipients/setting-channel-data.mdx
update link to slack integration
=> fix: update slack scope link

content/sdks/ios/push-notifications.mdx
Updating a few things in our PushNotification iOS docs based on some customer feedback and code changes within the sdk.
=> Updating docs with refactored ios code

content/in-app-ui/ios/components.mdx, content/in-app-ui/ios/customization.mdx, content/in-app-ui/ios/overview.mdx, content/sdks/ios/reference.mdx, data/sidebar.ts
Updating the iOS In App UI Documentation
=> Updated docs for the In App UI for iOS

content/preferences/overview.mdx
Updates the example app URL to use our custom domain.
=> Update demo URL to use custom domain

content/in-app-ui/react/preferences.mdx
Needed to make a few updates to the code samples for styling to apply correctly
=> fix: small code tweaks for styles

content/integrations/overview.md
Adds a note about sandbox mode not being supported for in-app.
=> fix: add in-app exception for sandbox mode

content/integrations/push/firebase.mdx
Try to do a better job of calling out web push support here for FCM. After looking at the existing docs, the steps are almost the same, so just tried a few small tweaks to make it more apparent that you could do web push here and added Algolia tags to make it show up in search
=> chore: try to highlight web push

content/integrations/in-app/knock.mdx
This update clarifies where to add an API response filter for an in-app channel.
=> chore: add instructions for API response filters

content/reference.mdx
Adds new message API filtering methods
=> chore: add new message api filtering docs

content/manage-your-account/audit-logs.mdx
Remove outdated information about audit log retention windows
=> chore: update audit log retention windows

content/reference.mdx
Documentation update for https://github.com/knocklabs/switchboard/pull/2544
=> chore: add optional `null` value for schedule repeats

content/designing-workflows/template-editor/overview.mdx, content/designing-workflows/template-editor/variables.mdx
Add docs for `$data` support
KNO-6396
=> feat: add support for  in template vars

content/concepts/workflows.mdx
Adds a section on archiving workflows
=> chore: add archive workflow section

pages/_app.tsx
=> chore: use display swap for font perf

content/designing-workflows/throttle-function.mdx, content/send-notifications/triggering-workflows.mdx
- Adds docs for trigger frequency
- Adds callout in throttles for trigger frequency
=> chore: trigger frequency doc updates

content/cli.mdx, content/designing-workflows/partials.mdx, content/designing-workflows/template-editor/reference-liquid-helpers.mdx, content/mapi.mdx, data/sidebar.ts, layouts/CliReferenceLayout.tsx, layouts/MapiReferenceLayout.tsx
- First draft of the partials docs
- Partial MAPI and CLI docs
[KNO-6056](https://linear.app/knock/issue/KNO-6056/%5Bdocs%5D-partials-documentation)
=> feat: partials documenation

content/integrations/extensions/data-sync.mdx
Adds details about the new Recipient Change Stream Prequel table available to enterprise customers.
PLA-347
=> chore(pla-347): recipient change stream docs

content/designing-workflows/partials.mdx
- Fix code block spacing
- add beta tag
=> fix spacing and add beta tag

content/designing-workflows/partials.mdx
=> CHORE: Remove beta tag on Partials doc

content/developer-tools/outbound-webhooks/event-types.mdx, content/reference.mdx, content/sdks/javascript/reference.mdx
Adds `message.interacted` metadata to docs
KNO-6717
=> chore: add interacted metadata docs

content/integrations/overview.md, content/integrations/sms/overview.mdx, content/integrations/sms/sinch-message-media.mdx, data/integrationsSidebar.ts
Docs for MessageMedia
KNO-6713
=> feat: add docs for sinch messagemedia

content/sdks/ios/quick-start.mdx
Updated some small sections on the ios quick start guide based on user feedback.
=> chore: clarify pk and userToken

content/guides/alerting.mdx
This PR adds the following callouts:
- one at the top to the example app repo
- one in the workflow section calling out the template gallery
Will follow up with a set of CLI instructions in the README of the example app
=> chore: add callouts for app and template

content/reference.mdx, content/send-notifications/triggering-workflows.mdx
Adds docs for workflow trigger validation
KNO-6818
=> feat: add docs for workflow trigger data validation

content/preferences/overview.mdx
Small fix to label for setting preferences in the Preferences overview
=> fix: set instead of get

content/concepts/users.mdx
Update the callout under the user identifiers section to note that `#` characters are not valid in a user ID.
https://docs-dhcleae8v-knocklabs.vercel.app/concepts/users#user-identifiers
=> chore: update callout to include # character

content/send-notifications/triggering-workflows.mdx
Remove beta callout for validating trigger data
=> chore: remove beta callout

content/designing-workflows/template-editor/overview.mdx, content/designing-workflows/template-editor/variables.mdx
- Move language to use `data.` to reference variables
- Fix template vars table
KNO-6914
=> feat: introduce `data` in template variables

content/manage-your-account/directory-sync.mdx
Updates the information for setting up directory sync to better align with our process.
I also removed the screenshot, as it's not necessary for customers to go into the dashboard to click to contact support (they can just email us directly).
https://docs-git-rt-update-directory-sync-knocklabs.vercel.app/manage-your-account/directory-sync#directory-sync-configuration
=> chore: update directory sync set up steps

content/send-notifications/tracking.mdx
Update tracked link documentation to include full list of new subdomains for link tracking.
=> chore: update tracked link domains

content/designing-workflows/delay-function.mdx
Add relative delay step type documentation for feature [Computed Delay Windows](https://www.notion.so/knockapp/Computed-delay-windows-fac767ee652048c4addc94207a3bc68a)
[KNO-7125](https://linear.app/knock/issue/KNO-7125/[docs]-add-docs-for-relative-delay)
TODO
=> feat(kno-7125): add relative delay documentation

content/in-app-ui/react/slack-kit.mdx
Updates the JWT example for custom SlackKit claims based on customer feedback
=> chore: update custom claims ex

content/concepts/audiences.mdx
Add a beta callout to audiences
[kno-7210](https://linear.app/knock/issue/KNO-7210/docs-beta-callout-audiences)
=> chore: add beta callout

content/reference.mdx
Specifies the max batch size for audience add/remove api requests
KNO-7211
=> chore: add pre-request member count limit to audience docs

content/designing-workflows/template-editor/variables.mdx
Expose prefs under recipient in template vars
=> chore: expose preferences under a recipient in template vars

content/preferences/quick-start.mdx
Remove Preferences quick start stub that was indexed into search
=> fix: delete stub that was indexed into Algolia

content/guides/going-to-production.mdx
Removes the checkboxes as those weren't clickable and visually confusing with the bullet points. 
Before:
After:
=> chore: remove checkboxes

content/reference.mdx, data/code/tenants/set.ts
Add note to tenant reference explaining the image mime type requirement for branding urls.
[KNO-7409](https://linear.app/knock/issue/KNO-7409/[docs]-update-tenant-branding-docs-to-outline-logo-and-icon-url)
=> chore(kno-7409): update tenant branding with url validation rules

content/designing-workflows/overview.mdx
Adds the branch function to supported functions under the designing workflows overview page. 
https://docs-git-rt-update-function-steps-supported-knocklabs.vercel.app/designing-workflows/overview#function-steps
=> chore: add branch function to designing workflows overview

content/designing-workflows/batch-function.mdx
Adding docs for batch w/ leading debounce. Very open to feedback!
KNO-7305
=> feat: add docs for batch w/ leading debounce

content/integrations/push/one-signal.mdx
A few small improvements, mainly formatting code and adding useful links.
=> chore: update OneSignal docs

content/concepts/objects.mdx, content/concepts/subscriptions.mdx, content/designing-workflows/template-editor/referencing-data.mdx, data/sidebar.ts
Adds new docs for working with the `user`, `tenant`, `object` filters in templates
KNO-7454
=> feat: add docs for working with dynamic references

content/designing-workflows/trigger-workflow-function.mdx
Fixes an incorrect link, a typo, and updates to align with the [style guide](https://www.notion.so/knockapp/Knock-writing-style-guide-9fd5eaf44be54994ad8741d1c86f20f1?pvs=4#62e29a1242e94ea192184f79b24d514e)
https://docs-git-rt-trigger-workflow-function-typos-knocklabs.vercel.app/designing-workflows/trigger-workflow-function
=> chore: small typo and style updates to trigger workflow function

content/managing-recipients/deleting-users.mdx
Updates the FAQ to clarify that you can delete a user via the dashboard while also recommending using the API when possible. 
https://docs-git-rt-update-deleting-user-dashboard-knocklabs.vercel.app/managing-recipients/deleting-users#frequently-asked-questions
=> chore: update FAQ about deleting users

content/manage-your-account/saml-sso.mdx
Updates the instructions for setting up SSO to better align with the current dashboard set up. 
https://docs-git-rt-update-sso-instructions-knocklabs.vercel.app/manage-your-account/saml-sso
=> chore: update SSO instructions

content/concepts/audiences.mdx
Add an FAQs section to the Audiences docs, with an entry for a customer question that we received around identifying missing users.
=> chore: add audiences faqs

content/in-app-ui/react/slack-kit.mdx
updates the property for the combobox
=> chore: update slackkit docs

content/integrations/sms/twilio.mdx
Callout that twilio supports bounces
=> chore: add docs for twilio bounce support

content/concepts/objects.mdx, content/designing-workflows/template-editor/referencing-data.mdx, data/sidebar.ts
Remove the beta callout for referencing data
=> chore: remove reference beta callout as it's open to all

content/integrations/sms/settings-and-overrides.mdx, data/integrationsSidebar.ts
Add docs for JSON overrides and to number overrides for SMS channels
=> feat: add docs for SMS overrides

content/designing-workflows/throttle-function.mdx
fixing a 404 error in SEM rush
=> chore: fix 404 error

content/developer-tools/management-api.mdx, content/mapi.mdx, layouts/MapiReferenceLayout.tsx
Added API ref and doc callout for previewing templates
=> feat: add docs for preview template endpoint

data/sidebar.ts
Updates a link in the sidebar that pointed at a redirect
=> fix: remove redirected link

content/integrations/sources/overview.mdx, content/integrations/sources/rudderstack.mdx, content/integrations/sources/segment.mdx
=> chore: fmt

content/getting-started/example-apps.mdx
Adds an SDK card for the marketplace example app
=> feature: add marketplace example app

content/integrations/email/postmark.mdx
Update docs to reflect Postmark sender update (`Meta` -> `Metadata`)
=> chore: update docs for postmark metadata

content/integrations/chat/slack/overview.mdx
=> chore: link to email-based user ID resolution docs from Slack overview

content/mapi.mdx
This PR updates the mAPI reference to describe how to set relative delays.
https://docs-eouax78zr-knocklabs.vercel.app/mapi#delay-step-definition
=> chore: add relative delays to mapi ref

content/reference.mdx, data/apiReferenceSidebar.ts
This PR adds the new bulk create schedules endpoint to our API reference.
=> chore: add bulk schedules endpoint

data/specs/mapi/openapi.yml, data/specs/mapi/stainless.yml
Adding mAPI open API specs so we can merge the control update pipeline: https://github.com/knocklabs/control/pull/4782
KNO-8064
=> feat: adding openapi specs so we can start automating builds

content/concepts/broadcasts.mdx, content/concepts/overview.mdx, content/concepts/workflows.mdx, data/sidebar.ts
First pass at writing some documentation for the Broadcasts concept. Would appreciate feedback!
KNO-7369
=> feat: broadcast docs for beta

content/concepts/broadcasts.mdx, content/reference.mdx
This PR fixes a couple small issues:
- language on Broadcasts docs
- HTTP method on API ref example for removing audience members
=> chore: small fixes

components/ui/CollapsibleNavItem.tsx, components/ui/NavItem.tsx, components/ui/Page/Sidebar.tsx, package.json, yarn.lock
=> adds collapsible sidebar items

content/developer-tools/agent-toolkit/getting-started.mdx, content/developer-tools/agent-toolkit/human-in-the-loop-flows.mdx, content/developer-tools/agent-toolkit/overview.mdx, content/developer-tools/agent-toolkit/providing-context.mdx, content/developer-tools/agent-toolkit/tools-reference.mdx, content/developer-tools/agent-toolkit/workflows-as-tools.mdx, content/developer-tools/agent-toolkit/working-with-environments.mdx, content/developer-tools/building-with-llms.mdx, content/developer-tools/mcp-server.mdx, data/sidebar.ts
This PR adds new docs pages under the "Developer tools" section for:
- Agent toolkit
- MCP server
- Building with LLMs
KNO-8425
=> feat: agent toolkit, mcp, and working with llms docs

content/concepts/audiences.mdx
- Adds small section on CSV upload to audiences docs. 
[KNO-8498](https://linear.app/knock/issue/KNO-8498/update-audience-docs-to-include-info-on-csv-upload)
=> feat: add info on csv upload to audiences docs

components/ui/Page.tsx, components/ui/Page/Sidebar.tsx, components/ui/Page/helpers.ts, lib/debounce.ts
The open / close and scroll functionality led to some jank, especially on slower machines. This PR reduces the amount of calls we make on scroll and leads to a much smoother sidebar UX
=> More performant sidebar

content/developer-tools/agent-toolkit/getting-started.mdx, content/developer-tools/agent-toolkit/human-in-the-loop-flows.mdx, content/developer-tools/agent-toolkit/overview.mdx, content/developer-tools/agent-toolkit/providing-context.mdx, content/developer-tools/agent-toolkit/workflows-as-tools.mdx, content/developer-tools/agent-toolkit/working-with-environments.mdx
Clean up agent toolkit based on latest in https://github.com/knocklabs/agent-toolkit/pull/20
=> chore: make updates prelaunch

.cursor/rules/styleguide.mdc, content/developer-tools/agent-toolkit/getting-started.mdx, content/developer-tools/agent-toolkit/human-in-the-loop-flows.mdx, content/developer-tools/agent-toolkit/overview.mdx, content/developer-tools/agent-toolkit/providing-context.mdx, content/developer-tools/agent-toolkit/tools-reference.mdx, content/developer-tools/agent-toolkit/workflows-as-tools.mdx, content/developer-tools/agent-toolkit/working-with-environments.mdx, content/developer-tools/building-with-llms.mdx, content/developer-tools/mcp-server.mdx, content/preferences/commercial-unsubscribe.mdx, data/sidebar.ts
* Fixing capitalization on Agent Toolkit
* Adding a cursor rules style guide to docs
=> Capitalization Agent Tookit + style guide

next.config.js
=> chore: agent url redirect

data/sidebar.json
Just needed to add these new pages to the LLMS text build pipeline. Will try to refactor this soon so there's not duplicate places where this lives.
=> fix: update llms-txt config

components/ui/Autocomplete.tsx, styles/index.css
Have to ensure the StaticSearch component matches the actual search exactly
=> Fixes header layout shift

components/Header/MinimalHeader.tsx, components/ui/Autocomplete.tsx, components/ui/CodeBlock.tsx, content/tutorials/alerting.mdx, content/tutorials/building-recurring-digests.mdx, content/tutorials/customer-webhooks.mdx, content/tutorials/implementation-guide.mdx, content/tutorials/migrate-from-courier.mdx, content/tutorials/modeling-users-objects-and-tenants.mdx, content/tutorials/overview.mdx, hooks/useInKeepSettings.ts, package.json, pages/_app.tsx, yarn.lock
** Describe what, why and how of the changes clearly and concisely. Add any additional useful context or info, as necessary. **
** List any todo items necessary before merging, if any. Delete if none. **
** Link to task(s) which this PR corresponds to. Example: [KNO-54](https://linear.app/knock/issue/KNO-54/create-a-pr-template) **
** Attach any screenshots or recordings to visually illustrate the changes, as necessary. Delete if not relevant. **
=> fix: fast-follows for docs 2.0 launch

components/ui/ApiSections.tsx, components/ui/Endpoints.tsx, components/ui/OverviewContent/Section.tsx, components/ui/Page.tsx, content/__api-reference/content.mdx, content/cli.mdx, data/apiReferenceSidebar.ts, data/sidebar.ts, pages/api-reference/index.tsx, pages/mapi-reference/index.tsx, styles/global.css
=> fix: Small fixes across the site, responsive API refs and more telegraph

content/concepts/subscriptions.mdx, content/designing-workflows/template-editor/overview.mdx, content/designing-workflows/trigger-workflow-function.mdx, content/developer-tools/outbound-webhooks/event-types.mdx, content/in-app-ui/android/sdk/push-notifications.mdx, content/in-app-ui/javascript/sdk/reference.mdx, content/in-app-ui/message-types.mdx, content/in-app-ui/react/slack-kit.mdx, content/in-app-ui/react/teams-kit.mdx, content/managing-recipients/identifying-recipients.mdx, content/managing-recipients/setting-channel-data.mdx, content/tutorials/migrate-from-courier.mdx, next.config.js
Fixes some links that should work
=> fix: SDK redirects

components/Meta.tsx, components/ui/ApiReference/ApiReference.tsx, components/ui/Page/Sidebar.tsx, layouts/CliReferenceLayout.tsx, pages/api-reference/[...slug].tsx, pages/cli/[...slug].tsx, pages/mapi-reference/[...slug].tsx
- Cuts build times from 12 minutes to 6 minutes (**100% improvement!** 🎉 )
- Improves search indexing compatibility
- Shuts up hydration warnings caused by `useLayoutEffect`
=> fix: build speeds

next.config.js
updates some non-perm redirects to perm
=> chore: make redirects perm

content/integrations/extensions/data-sync.mdx, content/integrations/extensions/heap.mdx, next.config.js
This last audit caught another one
=> chore: update reference redirect

components/ui/ContentActions.tsx
=> fix: capitalization of Markdown

components/ui/ApiReference/ApiReference.tsx, components/ui/Autocomplete.tsx, components/ui/Breadcrumbs.tsx, components/ui/CollapsibleNavItem.tsx, components/ui/NavItem.tsx, components/ui/Page.tsx, components/ui/Page/MobileSidebar.tsx, components/ui/Page/ScrollerBottomGradient.tsx, components/ui/Page/Sidebar.tsx, components/ui/Page/helpers.ts, components/ui/PageHeader.tsx, components/ui/SdkCard.tsx, layouts/CliReferenceLayout.tsx, layouts/DocsLayout.tsx, layouts/InAppUILayout.tsx, layouts/IntegrationsLayout.tsx, pages/index.tsx, styles/index.css, styles/responsive.css
Had to re-architect the menu a bit so that I can easily drop it into the mobile sidebar. Also figured out how to keep our beautiful scroll gradient functional.
=> feat: adds mobile nav

content/integrations/email/smtp.mdx
Adds a note about rate limits on auth for some SMTP relay servers.
=> chore: add mention of auth rate limiting for some smtp providers

components/ui/ContentActions.tsx
** Describe what, why and how of the changes clearly and concisely. Add any additional useful context or info, as necessary. **
** List any todo items necessary before merging, if any. Delete if none. **
** Link to task(s) which this PR corresponds to. Example: [KNO-54](https://linear.app/knock/issue/KNO-54/create-a-pr-template) **
** Attach any screenshots or recordings to visually illustrate the changes, as necessary. Delete if not relevant. **
=> fix: Markdown navigation URL clears hashes and queries

content/integrations/email/layouts.mdx
Adds info on new preview text feature and removes info on using pre-content for preview text.
=> feat: include info on preview text

.env.example, components/ui/Autocomplete.tsx, lib/content.server.ts, package.json, pages/[...slug].tsx, scripts/createApiSearchIndex.ts, scripts/indexApisForSearch.ts, styles/index.css, types.ts
=> feat: upgraded search to include API endpoints

content/developer-tools/agent-toolkit/getting-started.mdx
=> chore: update getting-started.mdx

content/developer-tools/migration-guides/node.mdx
Update node sdk migration guide info on identifying users
=> fix: update node sdk migration guide info on identifying users

components/Meta.tsx, components/ui/Autocomplete.tsx, styles/responsive.css
=> feat: small UX improvements for search on mobile

content/developer-tools/mcp-server.mdx
Just released: https://knocklabs.slack.com/archives/C06A1FCF9L3/p1749069273173859
https://www.cursor.com/changelog/1-0
http://docs.cursor.com/deeplinks
=> feat: add an add to cursor button

content/integrations/email/attachments.mdx
Updates the instructions for setting an attachment key in the new template editor.
=> chore: update attachment instructions for new template editor

content/developer-tools/agent-toolkit/tools-reference.mdx
=> chore: update available tools

content/developer-tools/agent-toolkit/tools-reference.mdx, content/developer-tools/mcp-server.mdx
- Improve MCP setup instructions to use env vars
- Improve MCP tools examples
- Add category to available tools
=> chore: improve mcp tools doc

data/specs/api/customizations.yml
Updates the user description per the [API QA](https://www.notion.so/knockapp/Generated-API-QA-1d9c5a20997880ae97e3d5368635b38c?source=copy_link#1dcc5a20997880ac8a60fb3ec4368fdd).
https://docs-git-rt-kno-8910-knocklabs.vercel.app/api-reference/users/
[KNO-8910](https://linear.app/knock/issue/KNO-8910/docs-update-users-endpoints)
=> chore(kno-8910): Update users description

data/sidebars/mapiOverviewSidebar.ts, data/specs/mapi/customizations.yml, data/specs/mapi/openapi.yml, data/specs/mapi/stainless.yml
- Update OpenAPI spec to latest for mAPI
- Update stainless config
=> chore: manually update mapi spec

content/send-notifications/tracking.mdx
adding section on enabling custom domains to link tracking docs
=> feat: enhance tracking documentation with custom domain section

content/send-notifications/tracking.mdx
Updates the list of tracked link domains to the latest, including full series for future-proofing.
=> chore(kno-9085): update tracked link domains

content/developer-tools/agent-toolkit/tools-reference.mdx
Adds guides tools to agent toolkit reference
=> chore(kno-9178): add guides tools

content/in-app-ui/react/headless/preferences.mdx, content/in-app-ui/react/overview.mdx, content/in-app-ui/react/sdk/reference.mdx, data/sidebars/inAppSidebar.ts, yarn.lock
This PR introduces comprehensive documentation for the new `usePreferences` React hook, enabling developers to build custom notification preference UIs.
- A new headless UI guide for building custom preference UIs: `content/in-app-ui/react/headless/preferences.mdx`.
- Detailed API reference for `usePreferences` under the React SDK section: `content/in-app-ui/react/sdk/reference.mdx`.
- Navigation updates to make the new documentation discoverable.
=> chore: document new usePreferences hook

content/cli.mdx, content/concepts/broadcasts.mdx
Broadcast per recipient data docs
=> feat(kno-9236): add broadcast per-recipient data docs

content/designing-workflows/partials.mdx
This PR attempts to clarify a few things in the existing partials docs, and adds a section on updating an existing partial to set expectations about how those changes are published to any resource dependencies in your environment that use the partial.
=> chore(kno-8886): clarify partials docs

.cursor/rules/tutorial-writing.mdc, claude.md
This pr adds guidelines for writing tutorials to claude.md and cursor/rules
Feel free to add anything I missed or if you encounter rules we should add in the future please update.
=> feat: add claude.md and cursor rules for writing tutorials

content/in-app-ui/guides/render-guides.mdx
Quick change to add an export to guides example component so you can more easily copy/paste example code
=> chore: add export to guides ex. 

content/tutorials/sending-web-push-notifications-with-fcm.mdx, data/sidebars/tutorialsSidebar.ts
Adds a tutorial on using FCM and Knock to do web push
=> feat: add web push tutorial
